insert into "categories" ("name") values
('Jerawat'),
('Vitamin D'),
('Alat Bantu Dengar'),
('Perban'),
('Susu'),
('Kontrasepsi & Hormon'),
('Anti Virus'),
('Mineral'),
('Hidung Tersumbat'),
('Kebutuhan Covid-19'),
('Krim Ruam'),
('Perlak & Popok Dewasa'),
('Demam & Nyeri'),
('Nasal Care'),
('Nasal Spray & Dekongestan'),
('Hipertensi'),
('Urinal'),
('Obat Onkologi & Imunosupresan'),
('Obat Kanker'),
('Kulit'),
('Susu Formula Bayi'),
('Acne Treatment'),
('Kuku'),
('Jantung & Hati'),
('Kondisioner'),
('Anti Inflamasi'),
('Pil Kontrasepsi'),
('Masalah Pencernaan'),
('Perlengkapan Menyusui'),
('Obat Imunosupresan'),
('Serat'),
('Asma'),
('Badan, Gigi, Rambut'),
('Penawaran Special'),
('Minyak Ikan'),
('Aksesoris'),
('Alat Tes Mandiri'),
('Suplemen Kesehatan'),
('Mata'),
('Solusi Aman Disfungsi Ereksi'),
('Antibiotik'),
('Batuk dan Flu'),
('Hormon Wanita'),
('Perlengkapan Pembersih'),
('Produk Konsumer Penyakit Jantung'),
('Obat Diabetes'),
('Kecantikan & Perawatan Diri'),
('Enzim Pencernaan'),
('Obat & Perawatan'),
('Produk Kulit Eksim Pilihan'),
('Otak'),
('Grooming'),
('Shampoo'),
('Perawatan Herbal'),
('Cuaca Panas'),
('Susu Dewasa'),
('Peralatan Makan'),
('Obat Rutin'),
('Perangkat & Peralatan'),
('Popok'),
('Multivitamin'),
('Pengukur Tekanan Darah'),
('Pengobatan Covid'),
('Vitamin E'),
('Saluran Kemih & Prostat'),
('Nutrisi'),
('Vitamin Keluarga s.d 35%'),
('Asam Lambung & GERD'),
('Alergi'),
('Anemia'),
('Perawatan Tubuh'),
('Tulang & Sendi'),
('Gatal, Kering & Merah'),
('Perawatan Rambut'),
('P3K'),
('Kondisi Kulit'),
('Pelega Tenggorokan'),
('Makanan Khusus'),
('Dermatitis & Eksim'),
('Deodoran & Pewangi'),
('Tulang & Sendi Sakit'),
('Antivirus'),
('Vitamin & Suplemen'),
('Lainnya'),
('Obat Lainnya'),
('Mual & Muntah'),
('Kesehatan Seksual'),
('Gula Diabetes'),
('Penurun Berat Badan'),
('Insulin'),
('Produk ISPA'),
('Perlengkapan Mandi'),
('Lensa Kontak Plano'),
('Kesehatan Jantung'),
('Ramadhan'),
('Kesuburan & Lainnya'),
('Kesehatan & Imun'),
('Antiseptik & Disinfektan'),
('Infeksi'),
('Sun Care'),
('Bayi & Anak'),
('Kandung Kemih & Ginjal'),
('Menstruasi, Kontrasepsi dan Hormon'),
('Tes Gula Darah'),
('Vitalitas & Stamina'),
('Diabetes'),
('Stoking Kompresi'),
('Balsem & Minyak Esensial'),
('Perawatan Ibu'),
('Obat & Suplemen'),
('Penambah Nafsu Makan'),
('Susu Medis Khusus'),
('Ramadhan (not used)'),
('Diet, Sehat & Bugar'),
('Untuk Sehari-Hari'),
('Kesehatan Mental'),
('Batuk & Flu'),
('Mata & Bibir'),
('Kecantikan'),
('Terapi Panas & Dingin'),
('Masalah Mata'),
('Produk Susu Pilihan'),
('Kebutuhan Pria'),
('Diare'),
('Obat Jantung'),
('Vitamin Import'),
('Pria'),
('Produk Konsumer Diabetes'),
('Eksim'),
('Perawatan Kulit Berjerawat'),
('Wajah'),
('Wanita'),
('Lensa Kontak'),
('Makanan Kucing'),
('Suplemen & Herbal'),
('Ibu dan Anak'),
('Kehamilan & Menyusui'),
('Produk Susu'),
('Rambut, Kulit & Kuku'),
('Perawatan Kewanitaan'),
('Penyakit Jantung'),
('Tulang & Gigi'),
('Pelindung Lutut'),
('Obat'),
('Beauty Enhancer'),
('Lensa Kontak Minus'),
('Disfungsi Ereksi'),
('Sanitizer & Antiseptik'),
('Alat Monitoring Diabetes'),
('Diet'),
('Test Pack'),
('Persendian'),
('Alat Bantu Mobilitas'),
('Termometer'),
('Untuk Bayi & Anak'),
('Imunitas'),
('Relaksan Otot'),
('Lensa'),
('Saluran Pencernaan'),
('Sembelit & Wasir'),
('Obat Tetes Telinga'),
('Produk Alami'),
('Menopause'),
('Susu Khusus'),
('Vitamin Anak'),
('Perawatan Wajah'),
('Probiotik'),
('Lanset, Jarum & Swab'),
('Infeksi Kulit'),
('La Roche Posay'),
('Ginjal & Kandung Kemih'),
('Kesehatan Pencernaan'),
('Makanan Anjing'),
('Vitamin Tulang & Otot'),
('Kontrasepsi Oral'),
('Jantung'),
('Penopang Tubuh'),
('Perawatan Pria'),
('Tulang & Osteoporosis'),
('Kesuburan & Kehamilan'),
('Popok & Tisu Basah'),
('Pereda Gatal'),
('Makanan'),
('Ibu & Anak'),
('Perawatan kulit'),
('Sariawan & Herpes Mulut'),
('Gangguan Kesuburan'),
('Snack Sehat'),
('Herbal'),
('Minyak Angin & Balsam'),
('Perawatan Hewan'),
('Obat Kumur'),
('Plester Penurun Panas'),
('COVID-19'),
('Asam Lambung'),
('Obat Alergi'),
('Menstruasi dan Kehamilan'),
('Alat Monitoring'),
('Demam'),
('Kesehatan Prostat'),
('Anti Nyeri'),
('Perlengkapan'),
('Kolesterol'),
('Alat Kesehatan'),
('Monitoring & Pengelolaan'),
('Makanan & Nutrisi'),
('Mulut & Tenggorokan'),
('Otot, Tulang dan Sendi'),
('Lebaran'),
('Masalah THT'),
('Kebutuhan Ibu'),
('Oximeter'),
('Imunitas & Antioksidan'),
('Perawatan Jerawat'),
('Perawatan Diri'),
('Balsem & Minyak'),
('Menstruasi'),
('Tisu Basah'),
('Kosmetik & Kecantikan'),
('Hemat Borongan'),
('Madu & Kurma'),
('Vitamin A, B & E'),
('Obat Herbal'),
('Penambah Berat & Otot'),
('Antibiotik & Anti Jamur'),
('Produk Kesehatan'),
('Orang Dewasa'),
('Kesehatan Mulut & Tenggorokan'),
('Kebutuhan Bayi & Anak'),
('Labore'),
('Oksimeter'),
('Inhaler'),
('Health Corner'),
('Langganan'),
('Cairan Lensa Kontak'),
('Dekongestan & Minyak'),
('Acne Patch & Gel'),
('Makanan & Snack'),
('Dewasa'),
('Perawatan Kecantikan'),
('Telon & Kayu Putih'),
('Otak & Saraf'),
('Anak'),
('Batuk, Pilek & Flu'),
('Demam & Sakit Kepala'),
('Perawatan Tangan'),
('Produk Minuman'),
('Supplement Pria'),
('Suplemen Khusus'),
('Pelindung'),
('Medicated Skin'),
('Infeksi Cacing'),
('Habbatussauda & Zaitun'),
('Vitamin & Herbal'),
('Antiseptik'),
('Imun Booster'),
('Kesehatan Bayi & Anak'),
('Penyangga Tangan'),
('Pereda Demam & Nyeri'),
('Mual & muntah'),
('Makanan & Minuman'),
('Perawatan Kulit'),
('Perawatan'),
('Masker & Pelindung'),
('Suplemen'),
('Pisau Cukur'),
('Asam Urat & Radang Sendi'),
('Vitamin C'),
('Susu Formula Anak'),
('Kondom & Pelumas'),
('Antijamur'),
('Sariawan'),
('Kelainan Darah'),
('Kebersihan Hidung'),
('Best Deals sd 50%'),
('Gangguan Tidur'),
('Obat Kumur Antiseptik'),
('Nutrisi Lainnya'),
('Lansia'),
('Nutrisi Bersalin'),
('Produk Sekali Pakai'),
('Antioksidan'),
('Vitamin dan Herbal Jantung'),
('Madu'),
('Sehat Hemat'),
('Healthy Lifestyle'),
('Suplemen Diabetes'),
('Nutrisi Diabetes'),
('Kaleng Oksigen'),
('Perawatan Asma'),
('Covid-19'),
('Perangkat & Aksesoris'),
('Alat Monitoring Penyakit Jantung'),
('Tisu Alkohol & Jarum'),
('Jarum Insulin'),
('Perawatan Luka'),
('Swab Alkohol'),
('Jarum Tes'),
('Timbangan'),
('Celana Sunat'),
('Mainan');
