insert into "manufacturers" ("name") values
('Etercon Pharma'),
('Plasmindo Prima Sejahtera'),
('Aspen'),
('LLOYD PHARMA INDONESIA'),
('Ciubros Farma'),
('Gholiban'),
('Kittenspark Indonesia'),
('Tirta Sarana Sukses'),
('Burroughs Wellcome'),
('Tresno Jamu Indonesia'),
('ASIACAPITAL UTAMA INDONESIA'),
('Mitra Pharma Indonesia'),
('Al-Amir'),
('Social Bella Indonesia'),
('Totalcare Nutraceutical'),
('Meccaya'),
('Yahi Utama'),
('Sato Pharmaceutical'),
('Maniswangi'),
('Kino Indonesia'),
('Enam Warna Indonesia'),
('Nellco'),
('Purusa Bhakti'),
('Bagus'),
('Cendo Pharmaceutical'),
('Gabag Indonesia'),
('Saka Farma'),
('Herbal Nusantara'),
('Prima Solusi Medikal'),
('Industri Jamu dan Farmasi Sido Muncul'),
('Elanazma Prima'),
('Intijaya Meta Ratna Farma'),
('Apex Bio Tech'),
('Perfect Companion Indonesia'),
('Aimskincare Manufacturing Indonesia'),
('AstraZeneca'),
('Citra Medikasa'),
('Kebayoran Pharma'),
('Vermindo'),
('Gemilangsakti Farmindo'),
('Interbat'),
('Puspa Pharma'),
('Dami Sariwana'),
('SOMAN INDONESIA'),
('Pharos'),
('Basmallah Food'),
('Cahyadi Mulia Nugraha'),
('Promedrahardjo Farmasi Industri'),
('Diapro'),
('Rama Cipta Mandiri'),
('Paragon Technology & Innovation'),
('Madu Murni Nusantara'),
('Softto Company Limited'),
('Holisticare'),
('Church & Dwight UK Limited'),
('Asia Pacific Fortuna Sari'),
('Bintang Kencana Anugrah'),
('Sakara Mandiri Semesta'),
('Solas Langgeng'),
('GEA Medical'),
('Madura Utama Mandiri'),
('WICAKSANA OVERSEAS INTERNATIONAL'),
('Samco Farma'),
('Imfarmind'),
('Yichang Tianmei International Cosmetics Ltd'),
('Prima Centra Medikacitra'),
('Jayamas Medica Industri'),
('Mahesa Pusaka Asli'),
('Tanqa Putra Jaya'),
('Inti Citra Agung'),
('Fahrenheit'),
('Taishan Alkes Indonesia'),
('Indofood'),
('Dewi Tunjong'),
('MAMI '),
('PJ SHINSE TAN'),
('HERBALINDO CITRA MANDIRI'),
('NOSIN INDONESIA'),
('Katamata'),
('SIP Farma'),
('Kobayashi Pharmaceutical Indonesia'),
('Ultra Sakti'),
('Makarizo Indonesia'),
('Eli Lilly'),
('Supra Ferbindo Farma'),
('DSG Surya Mas Indonesia'),
('Yupi Indo Jelly Gum'),
('Kaminomoto Co'),
('Uni Indo Utama'),
('Dewi Bulan Djoyo'),
('Bintang Kupu-Kupu'),
('Macrocitra Ardanasejati'),
('Aventis Pharma'),
('Ikezaki Tekindo Tama'),
('Tempo Scan Pacific'),
('Hassana Boga Sejahtera'),
('General Nutrition Corporation Pittsurgh'),
('Genero Pharmaceutical'),
('Sanofi Aventis'),
('Hexpharm Jaya'),
('Imedco Djaja'),
('Colgate Palmolive Indonesia'),
('P.K.G. Gelora'),
('Nutrimedindo Neutraceuticatama'),
('Inovasi Mitra Sukses'),
('Blessindo Anugrah Sentosa'),
('OneMed'),
('Abad Dua Satu Makmur'),
('Kaliroto'),
('Heaven Chemical Indonesia'),
('Asia Health Energy Beverages'),
('Dacco'),
('Wong To Yick Wood'),
('First Medipharma'),
('Bumi Tani Nusantara'),
('BSN Medical'),
('Herlina Indah Jakarta'),
('Matahari Sakti'),
('Taisho Pharmaceutical'),
('Hills'),
('Sari Enesis Indah'),
('Generic Manufacturer'),
('Integrated Healthcare Indonesia'),
('ALBIRUNI SUKSES BERSINAR'),
('Yarindo Farmatama'),
('Dodorindo Jaya Abadi'),
('Indordesa Nutritional Laboratories'),
('Ethica Industri Farmasi'),
('Eltra Raya Perkasa'),
('Merck Sharp Dohme Pharma'),
('Kartikawira Adisukses'),
('Sterling'),
('Prima Bumi Mandiri'),
('Pharmacore'),
('Kalventis Sinergi Farma'),
('Amal Mulia Sejahtera'),
('Midix Graha Farma'),
('Enseval Medika Prima'),
('Mecosin'),
('Multitrend Indo'),
('Capilano Honey Pty'),
('Pamperindo Prima'),
('Minorock Mandiri'),
('Mega Products'),
('Zena Nirmala'),
('LIFESCAN'),
('Rudy Hadisuwarno'),
('Terumo Indonesia'),
('Guardian Pharmatama'),
('Bromo Pharmaceutical Industries'),
('Coronet Crown Pharmaceutical Industries'),
('Novartis Indonesia'),
('Kharis Agung Putra Jaya'),
('Johnson & Johnson Indonesia'),
('OXYFRESH USA'),
('Farmasi Laurel'),
('Ikot Herba'),
('Corsa'),
('Media Griya Harmony'),
('MITRA RAJAWALI'),
('Cisarua Mountain Diary'),
('Medical Herbal'),
('Anugerah Mas Internasional'),
('Merpati Mahardika'),
('Bausch Lomb Indonesia'),
('Etica Sari Pratama'),
('Lo Ban Teng'),
('R-EXPO'),
('IPI'),
('Mam Internasional'),
('Japfa Comfeed Indonesia'),
('Armoxindo Farma'),
('Pharma Healthcare'),
('Nutrindo Jaya Abadi'),
('Tri Buwana Winatra Darya'),
('Inti Jaya'),
('HKQ- Mark'),
('Jogja Natural Herbal'),
('Erpha'),
('Gala Djaya Raya'),
('Rhea Pharmaceuticical Sciences Indonesia'),
('Falmaco Nonwoven Industri'),
('Pharmasi Binangkit'),
('Do Care'),
('Nin Jiom Medicine Manufactory (Hongkong) Ltd'),
('PJ Oriental'),
('Derma Science'),
('Harbat Farma'),
('Cakra Kencana'),
('Kalbe Farma'),
('Nose Herbal Indo'),
('NaturoMedica'),
('STAR POLARIS'),
('Sinar Kemiri'),
('Bevos Prima Center'),
('Nova Chemi Utama'),
('Gunung Subur Sejahtera'),
('Gondowangi'),
('Harapan Maju Indah'),
('Vita Health Indonesia'),
('Berlico Mulia Farma'),
('Tobbest Busindo'),
('Pigeon Corporation'),
('Faes Farma'),
('Graha Kerindo Utama'),
('Pertiwi Agung (Landson)'),
('Gunon International'),
('Bintang Toedjoe'),
('Intercallin Indonesia'),
('PJ Sari Wangi'),
('PIGEON'),
('Sukses Abadi Pharmindo'),
('Dankos Farma'),
('Konimex'),
('Sari Bunga Alam Lestari'),
('WYETH'),
('Griya Annur'),
('Kambium'),
('Arto Pharma Indonesia'),
('Markswin Beauty Products'),
('Akasha Wira International Tbk.'),
('Amarox Pharma Global'),
('Mahakam Beta Farma'),
('Tulus Indojaya'),
('Triple Ace Corporation'),
('Indocore Perkasa'),
('CMR Indonesia'),
('Prima Medika Laboratories'),
('PIM Pharmaceutical'),
('Continental Cosmetic'),
('NATURA LABORATORIA'),
('Ifars'),
('Les Laboratories Servier - France'),
('Gelflex Indonesia'),
('Maxima Asta Wisesa'),
('Dragon Prima Farma'),
('Sea Quill In'),
('FC BIO SANITARY'),
('Tresno Joyo'),
('Chicco'),
('Avico'),
('Saraka Mandiri Semesta'),
('Mandiri Nugraha Ajitunggal'),
('Pusat Riyal Amanah'),
('Bima Artha'),
('Gesunde Medical'),
('Easton Kaleris Indonesia'),
('Jaya Berkat Utama'),
('Polytouch'),
('Nyonya Meneer'),
('Joenoes Ikamulya'),
('BECTON DICKINSON INDONESIA'),
('DRC'),
('Global Onkolab Farma'),
('Natra Bio'),
('Steril Medica Indonesia'),
('Infion'),
('Mandom Indonesia'),
('Mandom Indonesia Tbk'),
('Biopol Global Co.Ltd'),
('Yung Shin Pharmaceutical Indonesia'),
('LF ASIA Marketing Indonesia'),
('Medifarma'),
('Citra Usaha Lamindo'),
('Kalbe Morinaga Indonesia'),
('laive'),
('B. Braun'),
('Setia Kawan Abadi'),
('Ferron Par Pharmaceutical'),
('Montavit Pharma'),
('Pan Pacific Development'),
('Kino group'),
('Triyasa Nagamas Farma'),
('Deltomed Laboratories'),
('Natura Nuswantara Nirmala'),
('Eco Living'),
('Fabindo Sejahtera'),
('Sinar Herba Radix'),
('Golden Westindo Artajaya'),
('Merck Indonesia'),
('Young Young'),
('Sensi'),
('Glaxo Wellcome Indonesia'),
('Mega Pratama Medicalindo'),
('Shiseido Cosmetics Indonesia'),
('Surya Dermato Medica Laboratories'),
('Mayora Indah Tbk'),
('Novell Pharmaceutical Laboratories'),
('Laniros Dian Pharma'),
('Air Mancur'),
('WECARE'),
('Avizor'),
('Tunggal Sila Farma'),
('Mulia Farma Suci'),
('Abbott'),
('Tempo Natural Products'),
('Sekar Utami'),
('Nufarindo'),
('The Univenus'),
('Fashindo Raja Perkasa'),
('Sarana Indinatas Primatema'),
('LION WINGS'),
('Sinergi Adimitra Jaya'),
('Walter Ritter Gmbh'),
('Hasanayu Putri Jelita'),
('Arista Latindo'),
('Allmedicus'),
('Millennium Pharmacon'),
('Simex'),
('Smith & Nephew'),
('Asia Topindo Megajaya'),
('Mitra Asa Pratama'),
('Trias Sukses Dinamika'),
('Bio Oil Research LTD, England'),
('Victoria Care Indonesia'),
('Aimfood Manufacturing Indonesia'),
('Vonix Latexindo'),
('Fonterra Brands Indonesia'),
('Darwin Jamu Godok Indonesia'),
('MERSIFARMA'),
('Marion Sam'),
('Citradarsana'),
('Kali Kurnia'),
('Sanghiang Perkasa'),
('Sekawan'),
('Saras Subur Abadi'),
('Herbal Revival'),
('Baby Safe'),
('Herbal Indo Utama'),
('Kirin'),
('SINTHE UTAMA INDONESIA'),
('Nutrimax'),
('Sinar Antjol'),
('Royal Canin'),
('Tropica Mas Pharmaceutical'),
('Esa Prima Solusi'),
('Ben Sehat Sejahtera'),
('Vita Shopindo'),
('Global Mega Principal'),
('GAN INDONESIA'),
('Coronet Crown'),
('DKT International'),
('Giovan'),
('Dr. P'),
('Mega Utama Medica'),
('Bison Industri Farmasi'),
('Biotek Farmasi Indonesia'),
('Otsuka Indonesia'),
('Organon Pharma Indonesia'),
('HISAMITSU'),
('Fresenius Kabi'),
('Buana Intiprima Usaha'),
('Finusolprima Farma Internasional'),
('Rosary'),
('Garnier'),
('Capung Indah Abadi'),
('Perseroan Dagang dan Industri Farmasi Afiat'),
('Cap lang'),
('Omron Healthcare Indonesia'),
('Haijen Kosmetik'),
('Royal Medicalink Pharmalab'),
('Unimax Power'),
('Kharisma Food Indonesia'),
('Djojonegoro'),
('Eagle Indo Pharma'),
('Alam Sada'),
('Jamu Iboe Jaya'),
('Natural Product'),
('Intra Aries'),
('Ever Beauty Corporation'),
('Inti Cosmetic Lestari'),
('MUDI LABORATORIES'),
('Maharani Foot Care'),
('Dua Lima Industries'),
('NUTRISAINS'),
('Caltera Biobiru Nusantara'),
('Loria Cosmetics'),
('CCM Pharmaceutical'),
('Kino Petworld Indonesia'),
('Metiska Farma'),
('La Pointique International'),
('The Tool Health'),
('Brataco'),
('Dua Putra'),
('Tirta Anugerah Mandiri'),
('Arkstarindo Artha Makmur'),
('Husen S Prima Mandiri'),
('Unza Vitalis'),
('Zambon'),
('BAF Bekasi - Indonesia'),
('Servier'),
('Panca Talenta Mas'),
('Pillars Cosmetiklon Indonesia'),
('Rudy Soetadi'),
('Industri Djamu Dan Pharmasi Tjap Djago'),
('Balatif'),
('Novapharin'),
('Softex Indonesia'),
('Eres Revco'),
('Serenity Indonesia'),
('Caprifarmindo'),
('Iwaki Pyrex'),
('Tamba Waras'),
('Tarunakusuma Purinusa'),
('Gracia Pharmindo'),
('Holi Pharma'),
('Fidia Farmaceutici'),
('Sagami Rubber Industries'),
('Danpac Pharma'),
('Wings Surya'),
('Nutracare'),
('Mersifarma Tirmaku Mercusana'),
('Graha Megatama Indonesia'),
('Metro Drug Indonesia'),
('Afiat - Indonesia'),
('Exmon'),
('Aroma Prima Livindo'),
('Sejahtera Lestari Farma'),
('Actavis'),
('Joya Hougan Lestari'),
('Candra Nusantara Jaya'),
('Dos ni Roha'),
('Kalbe Blackmores Nutrition'),
('Menarini Indria Laboratories'),
('Wings Indonesia'),
('VICOMAS INTERNATIONAL'),
('Karniel Pacific Indonesia'),
('Rohto'),
('Dipa Pharmalab Intersains'),
('Sehat Secara Alami'),
('Sunthi Sepuri'),
('Inti Sumber Hasil Sempurna'),
('Oculus Indonesia'),
('Alpharma'),
('Happy Family Brands'),
('Urban Indo Manufaktur'),
('Global Chemindo'),
('Apex Pharma Indonesia'),
('Evo Nusa Bersaudara'),
('Ind Diagnostic Inc'),
('Tritunggal Sinarjaya'),
('Sun Pharmaceutical'),
('Sukses Abadi Raya'),
('Bufa Aneka'),
('Transfarma Medica Indah'),
('Syifa Herbal Alami'),
('KAO Indonesia'),
('Kinocare Era Kosmetindo'),
('Hoyu'),
('Alam Agung Lestari'),
('Indo Abadi Sari Makmur'),
('Phyto Kemo Agung'),
('Indomed Berkat Jaya'),
('Mega Medika Multianugerah'),
('Indomarco Adi Prima'),
('Lucas Djaja'),
('Jadied International'),
('Kimberly Clark'),
('Mitra Mas Sentosa'),
('TAZZAKA GROUP'),
('Escolab'),
('Immortal Pharmaceutical Lab'),
('Promed'),
('Heptasari Unggul'),
('SAINSGO KARYA INDONESIA'),
('Graha Farma'),
('The Himalaya Drug Company'),
('Prima Medika Labotaries'),
('Herlina Indah'),
('Gizi Indonesia'),
('Yakult Indonesia Persada'),
('Adas Indonesia'),
('Sterindo Medika'),
('TRADIMUN GRESIK'),
('Exoticon'),
('Arnez'),
('Paragon Technology and Innovation'),
('Danone'),
('PIERROT'),
('Beurer'),
('Herba Utama'),
('Hexa Medika Pratama'),
('Brands Suntory Indonesia'),
('Duta Intidaya'),
('Empro'),
('Reckitt Benckiser'),
('Gratia Husada Farma'),
('Sydna Farma'),
('None'),
('SSL International'),
('Itrasal'),
('Anak Mas Sakti'),
('Kelly International Cosmetic'),
('Tri Megah Makmur'),
('Cahaya Natural Botanikal'),
('Min Makassar'),
('Intrafood Singabera Indonesia'),
('Madurasa Unggulan Nusantara'),
('RISTRA LABORATORIS INDONESIA'),
('Habbasyi Niaga Utama'),
('Wajar Jakarta'),
('Advanced Bio-Technologies'),
('Nirwana Lestari'),
('Yuri'),
('Delta Atsiri Prima'),
('BIO-LIFE MEDILAB'),
('UCB Pharma'),
('Kosmetikatama Super Indah'),
('YSP Industries Indonesia'),
('Al-Shifa'),
('Klaper'),
('Combiphar'),
('Beiersdorf Indonesia'),
('Henson Farma'),
('Owen Mumford'),
('Galenika'),
('Nutricia'),
('Mahakarya Sukses Internasional'),
('Sampharindo'),
('Golden Coral Corporindo'),
('Palem Mustika'),
('Maisya Makmur'),
('Dion Farma Abadi'),
('Novarindo'),
('Sapta Sari Tama'),
('SC Johnson & Son Indonesia '),
('Kimia Farma'),
('Tirta Surya'),
('Tanabe Indonesia'),
('Mega Lifesciences'),
('Ricola LTD-Luar Negeri'),
('Nulab Pharmaceutical Indonesia'),
('Roche'),
('Sano Gratia Farma'),
('Terapi Alam Nabati'),
('Multi Sari Idaman'),
('Catur Dakwah Crane Farmasi'),
('Sari Husada Generasi Mahardika'),
('Optindo Suryatama'),
('Al-Afiat Sehat Alami'),
('Mustika Ratu'),
('Alfa Internal Optindo'),
('GlaxoSmithKline Indonesia'),
('Global Multi Pharmalab'),
('Orindo'),
('Gautama Indah Perkasa'),
('Mecosin Indonesia'),
('Sidola'),
('Al-Jazira'),
('Rohto Laboratories Indonesia'),
('Jamu Air Mancur'),
('Amerta Indah Otsuka'),
('Otto Pharmaceutical Industries'),
('Meprofarm'),
('Sebapharma'),
('Procter & Gamble (P&G)'),
('Mutiara Mukti Farma'),
('Toga Nusantara'),
('Watson'),
('Perdana Sakti Indonesia'),
('Nicholas Laboratories'),
('Barclay'),
('Trifa Raya Laboratories'),
('AND'),
('Sunbulah Group'),
('BDI Pharma'),
('Heinz ABC Indonesia'),
('Innovation Healthcare Indonesia'),
('Beauty Kasatama'),
('Yupharin Pharma'),
('Pacific Image Internasional'),
('Errita'),
('Anerle'),
('Industri Kecil Obat Tradisional Bokashi'),
('Galenium Pharmasia Laboratories'),
('Rembaka'),
('Kasa Husada Wira Jatim'),
('Pyridam Farma'),
('Tawon Jaya Makassar'),
('Sampharindo Perdana'),
('Mitra Insan Sejahtera'),
('Gloria Origita'),
('Henkel KGaA'),
('HOE PHARMA'),
('MAPA Gmbh'),
('Mahkotadewa Indonesia'),
('Natures Product Inc'),
('EGO Pharmaceutical'),
('Pratapa Nirmala (Fahrenheit)'),
('Dexa Medica'),
('Sanbe Farma'),
('Ultra Prima'),
('BIO STRATH'),
('Kors Beautipedia Permata'),
('Indocare Citra Pasific'),
('Alcon'),
('Sekarguna Medika'),
('Tata Global Sentosa'),
('Pers. Madu Am'),
('Agro Mitra Alimentare'),
('Teguhsindo Lestaritama'),
('Alam Hijau Selaras'),
('Selera Sweetsindo-Indonesia'),
('Suryaprana Nutrisindo'),
('Surabaya Indah Permai'),
('3M Indonesia Importama'),
('COTTONSOFT'),
('Daun Teratai'),
('Sunrica Mutiara'),
('Samudra Husada Lestari'),
('Distriversa Buanamas'),
('Irawan Djaja Agung'),
('Marin Liza'),
('Unicharm'),
('Basf Indonesia'),
('Vimel'),
('Era Ventura Indonesia'),
('Unirama Sukses Internasional'),
('Bina Karya Prima'),
('Erela'),
('Tunggal Idaman Abdi'),
('Baby Huki'),
('Perintis Pelayanan Paripurna'),
('Cheer Veen'),
('Radiant Sentral Nutrindo'),
('Philips'),
('Vitabiotics'),
('John Francis Laboratories'),
('Indo Sehat Lestari'),
('Medikon'),
('Happy Pet Indonesia'),
('Quamed'),
('Perusahaan Jamu Tradisional Dr Sardjito'),
('Mutifa Industri Farmasi'),
('Kobe Nutri Farma'),
('MITRA BLESSINDO PERKASA'),
('Kembang Bulan'),
('Vinda Internasional Indonesia'),
('UICCP Indonesia'),
('Cakra Daya Makmur'),
('Surya Lintas Nusantara'),
('Selamat Siswanto'),
('Molex Ayus Pharmaceutical'),
('Fira Herbalindo'),
('Metz Indonesia'),
('Enseval Putera Megatrading'),
('Bayer Indonesia'),
('Takeda'),
('Phytochemindo Reksa'),
('Indo Greenlife Harvest'),
('Eisai'),
('Mitra Bersama Jaya'),
('Marguna Tarulata Apk Farma'),
('Ikapharmindo'),
('TJE FU KU International'),
('Ichiya Indonesia'),
('Promedic Dyna Farma'),
('Sinde Budi Sentosa'),
('Asia Utama Indonesia'),
('Indofarma Global Medika'),
('Boehringer Ingelheim'),
('Harvest Supplement'),
('Priskila Prima Makmur'),
('Viva Cosmetics'),
('Magic Star'),
('Lapi Laboratories'),
('Pelangi Daun Sri Rejeki'),
('Industri Jamu Borobudur'),
('Triman Pharmaceutical'),
('Sinar Sosro'),
('Faratu'),
('HIMALAYA'),
('Meiji'),
('Medikon Prima Laboratories'),
('Sintesa Duta Sejahtera'),
('Wellness'),
('Barbara Walden Cosmetics'),
('Bernofarm'),
('Sari Bunga Alam Sejati'),
('Soho Industri Pharmasi'),
('Winner Industries'),
('Schwarzkopf'),
('Astellas'),
('Carus Pharma'),
('Sapharindo Perdana'),
('Aquasolve Sanaria'),
('Total Solusi Bersama'),
('Cussons Indonesia'),
('Varia Sekata'),
('L Oreal Indonesia'),
('Leo Agung Raya'),
('Heksatamaprima'),
('BIOPTIC TECHNOLOGY'),
('Pandurasa Kharisma'),
('Janssen Cilag'),
('Toya Konsep Alam'),
('Selpasindo Pharco'),
('Pharma Lab'),
('Easy Touch'),
('Binary Herbal Marketing'),
('Fitto Natura Medica'),
('Charmindo Mitra Raharja'),
('Natural Nutrindo'),
('Pharmacia, Searle'),
('Kusuma Food Indonesia'),
('Unilever'),
('Mega Esa Farma'),
('Allergan'),
('Walla Tritunggal'),
('Osadra Graha'),
('Artois Pharmaceutical'),
('Phapros'),
('Cedefindo'),
('Mundipharma Healthcare Indonesia'),
('Aksamala Adi Andana'),
('Biomed'),
('Rhodoid'),
('Nutrifood Indonesia'),
('Biofarmaka Indonesia'),
('Henna'),
('Nestle'),
('Futamed Pharmaceuticals'),
('Global Health Pharma'),
('Martha Tilaar'),
('Mead Johnson Indonesia'),
('Lotte Indonesia'),
('Medisindo Bahana'),
('Anugerah Pharmindo Lestari'),
('HERMED'),
('Zenith Pharma'),
('Lohmann & Rauscher'),
('Thermo One'),
('Erlimpex'),
('Novo Nordisk'),
('Martina Berto'),
('Indofarma'),
('Stiefel'),
('Afi Farma'),
('Pfizer'),
('Megasari Makmur'),
('Mam'),
('HAWLEY & HAZEL'),
('Bahagia Idkho Mandiri'),
('Rama Emerald Multi Sukses'),
('Sandai Farma'),
('Mamac Distribusi Indo'),
('Herbalindo Mandiri Sentosa'),
('Hawley & Hazel Distribution Indonesia'),
('Nesco'),
('avopharm'),
('Aura Gemilang Mandiri'),
('Enesis Group'),
('Sentosa Karya Gemilang'),
('Mars Symbioscience Indonesia'),
('Jamu Puspo Internusa'),
('Genesis Oral Higinis'),
('Dermanesia'),
('Tempo Utama Sejahtera'),
('Medline Industries'),
('Medistra'),
('ELESKA PRIMA TIGA'),
('Maha Putra Internusa'),
('Griff Prima Abadi'),
('Bima Mitra Farma'),
('Iris Internasional'),
('Albaik Herbal Indonesia'),
('Tumbuh Lestari'),
('Gasol Pertanian Organik'),
('GENTONG MAS'),
('Beta Pharmacon'),
('Cendo Pharmaceuticals Industries'),
('Bristol-Myers Squibb'),
('Navita Inti Prima'),
('Harsen'),
('Usaha Sekawan Farmasi Indonesia'),
('General Care'),
('Pabrik Pharmasi Zenith'),
('Aman Indah Makmur'),
('Sidomuncul'),
('Scitec Nutrition'),
('AFRA'),
('Sahabat Lingkungan Hidup'),
('San Sidarta'),
('Sido Muncul'),
('Eltean Luhur Kencana'),
('Chiuan Rway Enterprise LTD'),
('Multi Indocitra'),
('Samator Gas Industri'),
('Orang Tua'),
('Jasmine Food Internasional'),
('Yekatria Farma'),
('Mudita Karuna'),
('Darya Varia Laboratoria'),
('Jamu Hari Fatma'),
('Multiutama Disposindo Jaya'),
('Galderma'),
('Indonesia Kose'),
('Sinergia Beaute Indonesia');
