datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
  
  - name: loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false