export const templateSearch = [
  "Tiap Gram Mengandung: Camphora 250 Mg",
  "Per-Kaplet : Vit.A 3",
  "Jati Belanda (Guazuma Ulmifolia) 165 Mg",
  "attapulgite 600 mg",
  "meat and animal derivatives",
  "Methampiron 500 mg",
  "Lecithin murni 300 mg",
  "Forti-D 1000 IU Sirup 100 ml: Cholecalciferol (Vitamin D3) 1000 IU.Vitabumin Madu Ikan Gabus Sirup 130 ml: Madu",
  "ekstrak bawang putih 500 mg",
  "Levonorgestrel 0.75 mg",
  "Gula alami",
  "Setiap Tablet mengandung: Pureway C 500 mg",
  "Ekstrak Coffee arabica semen (Green coffee) 200 mg",
  "Per gram : Oxytetracycline HCl 30 mg",
  "Per-inhalasi/puff : Terbutaline sulfate 0.5 mg",
  "Roxithromycin 300 mg",
  "Tiap kapsul mengandung: - Blessed Thistle (Cnicus benedictus) Herb Extract 4:1 100 mg. - Ginger (Zingiber officinale) Rhizoma P.E 4:1 100 mg. - Chamomile (Matricaria recutita) Flos Extract 4:1 25 mg. - Peppermint (Mentha piperita) Folium Powder Extract 25 mg. - Curcuma xanthorrhiza Rhizoma Extract 25 mg. - Catnip (Nepeta cataria) Herba PE 4:1 75 mg. - Fennel (Foenicullum vulgare) Semen PE 4:1 75 mg. - Feverfew (Tanacetum parthenium) Flos Extract 5:1 25 mg. - Red Clover (Trifolium pratense) Herba Extract 50 mg. - Papaya (Carica papaya) Fructus Powder Extract 75 mg.",
  "Languatis Rhizoma",
  "menthol 15%",
  "Tiap 5 ml mengandung Sucralfate 500 mg",
  "Sterile isotonic solution containing Sodium chloride",
  "Maltodekstrin",
  "Risedronate Na 150 mg",
  "Timepidium Br 30 mg",
  "Tetracycline HCI 500 mg",
  "Sefiksime trihidrat 100 mg",
  "Lecithin 300 mg",
  "Rice*",
  "ceramosides",
  "Garciniae Pericarpium Extract : 330 mgAzadirachtae Folium Extract : 220 mg",
  "Ezetimibe 10 mg",
  "nGlucosamine HCl (Shrimp Shell) 500 mg",
  "Curcumae domesticae Rhizoma (kunyit) 18 mg",
  "Warfarin Na 2 mg",
  "Per 5 mL : Dimethylpolysiloxane 50 mg",
  "vitamin B1",
  "Mengandung: Mixed Beta Carotene",
  "AmLodipine Besylate 5 mg & Atorvastatin Ca 20 mg",
  "L-Mucin (Snail extract)",
  "Per 5 mL : Ekstr Silymarin phytosome 8.75 mg",
  "Purified water",
  "Tiap 10 Ml Mengandung Minyak Kayu Putih 10 Ml",
  "Warfarin",
  "Tiap 500 mg kapsul mengandung : -Serbuk Sonchi Folium ( Ekstrak daun tempuyung) 392 mg",
  "Donepezil HCl 5 mg",
  "Dextromethorphan hydrobromide 7.5 mg",
  "Aqua (Water)",
  "Vit.B1 100 mg",
  "Clindamycin phosphate 1.2%",
  "Per 5 mL : Cefixime trihydrate 100 mg",
  "Mengandung Balancing Seaweed Cucumber Extract",
  "Vitamin C (as Ascorbic Acid)",
  "Omega 3 asam lemak esensial",
  "Metformin 500 mg",
  "Talk",
  "Vit.B1 15 mg",
  "ketoprofen",
  "Bioflavonoids (from Citrus limon exocarp)",
  "Vitamin B1 50 mg",
  "Talc",
  "acidum salyticum 2%balsamun peruvianum 1%mantholum 0",
  "Vitamin A (as Beta-carotene)",
  "Per mL : Pirenoxine 0.05 mg",
  "Vitamin A 2000 iu",
  "Polymyxin B sulfate 50000 iu",
  "Derivat Arabinoxylan 250 mg",
  "Amoxicillin trihydrate 500 mg",
  "Astaxanthin 4 mg",
  "55% Water content",
  "Dextromethorphan HBr 0.1%",
  "Ofloxacin 0.3%",
  "PAMOL DROP: Paracetamol 60 mg",
  "Tiap kapsul lunak mengandung: 100% pure krill oil",
  "38% Water content",
  "dehydrated poultry protein",
  "Ipatropium Bromide 500 mcg",
  "Setiap Kapsul Mengandung : Ekstrak Morinda Citrifolia Fructus 200 Mg",
  "Ketorolac tromethamine 10 mg",
  "Cefadroxil Monohydrate 250 mg/5 ml",
  "Sucralfate 500 mg/5 ml",
  "Selenium 50 mcg",
  "lincomycin",
  "Deionised Water Sodium Laureth Sulfate Cocamidopropyl Betaine Cocamide DEA Perfume Glycol Stearate Glycerine Polyquaternium39 PEG7 Glyceryl Cocoate Sodium Chloride PEG120 Methyl Glucose Dioleate Citric Acid Goats Milk Powder Sodium PCA Aloe Vera Powder Tocopheryl Acetate Tetrasodium EDTA Methylisothiazolinone Methylchloroisothiazolinone",
  "Curcuma extrak 8%",
  "Eperisone HCI 50 mg",
  "Rice",
  "naproxen",
  "Per-tablet kunyah : Ca carbonate 1000 mg (setara dengan 400 mg elemen Ca)",
  "Calcium 250 mg",
  "Cefixime trihydrate 100 mg/5 mL",
  "Tiap 5 ml mengandung : Glyceryl guaiacolate 75 mg",
  "Fexofenadine",
  "Garcinia mangostana pericarpium extract (Kulit Manggis) 400 mg",
  "Pirenoxine 0.05mg/ml",
  "Nano Coenzyme Q10 (Ubidecarenone) 60 mg",
  "Desonide 0.5 mg",
  "Tiap tablet mengandung: Ekstrak Tribulus Terrestris extract 750 mg",
  "Betakaroten 5 mg",
  "Wintergreen oil",
  "Febuxostat 80 mg",
  "Tiap kapsul lunak mengandung Vitamin D3 (cholecalciferol 25 mcg) 1.000 IU",
  "PIRACETAM 800 MG",
  "lateks alami",
  "Oleum citronellae minyak sereh 2%",
  "Tamoxifen citrate 10 mg",
  "betamethasone",
  "Nirmatrelvir 150 mg dan Ritonavir 100 mg",
  "Ekstrak Annonae muricatae Folium (daun sirsak)400 mg setara dengan 2 g bahan segar.",
  "Laktosa",
  "kalsium 169mg",
  "Tiap 5 ml mengandung: Methisprinol 250 mg",
  "Calcium lactate 500 mg",
  "Pyrantel Pamoate 250 mg/5 ml",
  "Bawang Putih (Alii sativi Bulbus) 280 mg",
  "Setiap kapsul mengandung: Kunyit 250 mg",
  "Per gram : Fluocinolone acetonide 0.25 mg",
  "Paracetamol",
  "Vildagliptin 50 mg",
  "Purified water",
  "Per 5 mL : Cefadroxil monohydrate 250 mg",
  "Marine protein extr 250 mg",
  "Maltotreksim",
  "Calcium Citrate with Vitamin D",
  "Ketoconazole 2%",
  "Cassiae sennae folium 100 mg",
  "1 Norit 40 Tablet: Actived charcoal 125 mg. 2. Oralit 200 4.1 g 1 Sachet: Natrium klorida 0.52 gram",
  "Ekstrak Rimpang Jahe (Zingiber Officinale rhizoma extract)",
  "PureWay-C 500 mg setara dengan Vitamin C 450 mg",
  "Tiap kapsul mengandung : Vaccinnium myrtillus fructus extract (Bilberry fructus extract) 110 mg.",
  "Gula",
  "Tenoxicam 20 mg",
  "Per ml : 100.000 IU Nystatin.",
  "Tiap 5 ml : Dexchlorpheniramine Maleate 2 mg",
  "Per 5 mL: Erythromycin ethylsuccinate 200 mg",
  "Vit.A 4000 IU",
  "Tiap Kaplet Mengandung : Ubiquinone 30 mg",
  "Aromatherapy",
  "Ketoconazole",
  "Drospirenone 3 mg + Ethinylestradiol 0.03 mg",
  "Colloidal Silver 32 ppm",
  "Dabigatran etexilate",
  "Gipsum fibrosum 7.0 g",
  "- Asam Salisilat 2 % - Talk 98%",
  "Paracetamol 350 mg",
  "Tiap 5 ml sirup mengandung: Dextromethorphan HBr 10 mg",
  "Protein 15.2 g",
  "Vitex trifolia folium 333 mgZingiber officinale rhizome 83 mg Abrus precatorius folium 83 mgPhaleria macrocarpa fructus 67 mg",
  "Tiap tablet mengandung Candesartan Cilexetil 16 mg",
  "Selenium Sulfida 1%",
  "Tiap 5 ml mengandung:Diphenhydramine hydrochloride 12.5 mgAmmonium Chloride 125 mg",
  "Tuna",
  "Tetracycline 250 mg",
  "Amoxicillin trihidrat 500 mg",
  "Ekstrak bunga marigold mengandung lutein ester yang setara dengan 6 mg lutein 80 mg",
  "Parasetamol 650 mg",
  "domperidone",
  "Amiodarone HCl 200 mg",
  "Salix alba bark extract",
  "Tiap 10 g mengandung : Ekstrak Channa Striata 5000 mg",
  "Cefditoren pivoxil 30 MG",
  "Tiap kapsul mengandung Fluoxetine / Fluoksetin HCl 20 mg",
  "Tiap kapsul mengandung:Propolis 250 mg",
  "Hydroquinone 40 Mg",
  "Rivaroxaban 20 mg",
  "Vitamin D3 1 IU",
  "Tiap 5 ml mengandung:Ibuprofen 100 mg",
  "100mg vitamin B1",
  "Per gram : Mometasone Furoate 1 mg",
  "Glucosamine HCl 500 mg",
  "Alcohol Denat",
  "Ekstrak iChanna Striata 500 mg",
  "Dexamethasone micronized 0.75 mg",
  "Paracetamol 500mg",
  "Guaifenesin/ Glyceril Guaiacolat 100 mg",
  "Tiap ml : Polymixin B Sulfate 10.000 IU",
  "Per 5 mL : Dextromethorpan HBr 10 mg",
  "Laktosa",
  "Al(OH)3 400 mg",
  "maize flour",
  "Levetiracetam 500 Mg",
  "ethinylestradiol",
  "32% poultry hearts",
  "WATER",
  "Asam folat/ Folic acid 200mcg",
  "Per 5 mL: Cefixime 100 mg",
  "Vitamin A Palmitate 1000 IU; zinc sulfate 0.2 mg; phenylephrine HCl 1.0 mg",
  "Selenium sulfide 1.8%",
  "Per 5 ml : Metoclopramide HCl 5 mg",
  "Ekstrak Shopora Japonica L 100mg",
  "Ca carbonate 749.1 mg (setara dgn Ca 300 mg elemental)",
  "Tiap 5 ml mengandung: Paracetamol 120 mg",
  "",
  "Desoximetasone 2.5 m",
  "Silvercare",
  "Tiap 5 ml mengandung: Levodropropizine 30 mg",
  "camphora 20%",
  "Tipa 5 ml: Amoxicillin 125 mg",
  "Tiap 5 mL mengandung: Ibuprofen 200 mg",
  "Aqua",
  "tizanidine",
  "Vitamin D3 (cholecalciferol) 400 IU",
  "Paracetamol 500 mg",
  "Protein whey",
  "Taurine 1000 mg",
  "Aqua Glycerim",
  "Heparin Na 15 g",
  "Vitamin A Palmitate 1000 IU; zinc sulfate 0",
  "Tiap 5 ml mengandung Zinc sulfate 54",
  "Air",
  "Tiap 10 ml mengandung: Iberis amara totalis Flos Extract (Bitter Candytuft) 60 mg",
  "Glutathionine 500 mg",
  "Ekstrak Aloe Vera",
  "Setiap tablet mengandung Vitamin C (Ascorbic acid) 50 mg",
  "Tiap 5 ml sirup mengandung: Ekstrak Succus liquiritiae 167 mg",
  "Fe gluconate 250 mg",
  "Diltiazem HCl180 mg",
  "Thiamphenicol mengandung 500 mg",
  "Clopidogrel bisulfate 75 mg",
  "Camphor",
  "Vitamin A",
  "Tuna",
  "Chitosan 250 mg",
  "Paracetamol 400 mg",
  "Echinacea 250 mg",
  "Per-dosis spray/semprot : Mometasone Furoate 50 mcg",
  "Sitagliptin 100 mg",
  "Fish oil 10/50 EPA/DHA 500 mg",
  "Oleum Iecoris Ass 100 mg",
  "Ca carbonate",
  "Medroxyprogesterone acetate 10 mg",
  "Asam lemak Omega-3 (ALA",
  "Vitamin A 2000 IU",
  "Lutein ester 10% 50 mg",
  "meat and animal derivatives",
  "Ossein hydroxyapatite 800 mg",
  "Tiap sachet mengandung :- Natrium klorida 0.52 gram- Kalium klorida 0.3 gram- Trisodium sitrat dihidrat 0.58 gram- Glukosa anhidrat 2.7 gram",
  "Pemanis alami sorbitol",
  "Dehydrated poultry protein",
  "Ibuprofen 400 mg",
  "Rice",
  "Terbinafine HCl 1%",
  "Setiap sachet (7 ml) mengandung : Aluminium hydroxide dried gel 300 mg",
  "Triisostearyl citrate",
  "Spent grain wax",
  "Ammonium Chloride 125 mg",
  "Tiap 1 ml suspensi mengandung:Nystatin 100.000 IU",
  "Betamethasone 0.25 mg",
  "dehydrated poultry protein",
  "Helianthus Annuus Seed Oil",
  "Vitamin C 100 mg",
  "Tiap 10 ml mengandung:Thymol 10 mg",
  "Tiap kapsul mengandung : Acai (Euterpe oleracea Extract) 200 mg",
  "Empaglifozin 25 mg",
  "Aqua",
  "Gentamicin Sulphate equivalent to gentamicin 0.1%",
  "Imboost 10 Tablet: Echinacea 250 mg",
  "Per sachet (52g) : Protein 10g",
  "Maltodekstrin",
  "Tiap kapsul mengandung: Nigella sativa semen extract/ jintan hitam/ habbatussada 150mg",
  "Vitamin A",
  "Tiap kaplet mengandung paracetamol 500 mg",
  "Chlorzoxazone 200 mg",
  "Rice",
  "Morinda citrifolia fructus (mengkudu) 700 mg",
  "Loratadine 10 Mg",
  "Tiap tablet mengandung: zinc sulfate monohydrate 20 mg",
  "Phenylpropanolamine HCl 12.5 mg",
  "Venlafaxine",
  "Cyclopentasiloxane Cyclotetrasiloxane Dimethiconol Phenyl Trimethicone Fragrance Tocopheryl Acetate Soybean (Glycine Soja) Oil Aleurites Moluccana Seed Oil Polysilicone-15 Panthenyl Ethyl Ether Aloe Barbadensis Leaf Oil Retinyl Palmitate Argania Spinosa Oil Ascorbyl Palmitate",
  "Andrographidis Herba Extract 550mg",
  "Dextromethorphan HBr 7.5 mg",
  "Fe fumarate 90 mg",
  "Tiap tablet mengandung : - Glucosamine Sulfate (Shellfish) 750 mg. - Chondroitin Sulfate 90% (Bovine) 667 mg.- OptiMSM 250 mg.",
  "Purified Water",
  "corn",
  "Metil Salisilat 110 mg",
  "Colistin Sulfate (Polymyxin E. Sulphate) 1",
  "Gatifloxacin 3 mg",
  "Tiap tube mengandung Selamectin 15 mg",
  "Gypsum Fibrosum 144 mg",
  "Amlodipine",
  "Hpmc 5 Mg",
  "Gypsum Fibrosum 3",
  "Serat Inulin",
  "Per 5 mL: Diphenhydramine HCl 12.5 mg",
  "Chicken by-product meal",
  "Per-kaplet salut : glucosmine HCI 250 mg",
  "Tiap 5 ml mengandung Paracetamol 120 mg",
  "Tiap 5 ml sirup mengandung : Paracetamol 125 mg",
  "Ekstrak Phaleria macrocarpa Fructus 200 mg",
  "Dried Alumunium Hydroxide Gel",
  "ctm",
  "Astaxanthin 4mg",
  "Per ml Air laut Adriatik (Adriatic sea water).",
  "Meat and animal derivatives",
  "Gefitinib 250 mg",
  "Oxomemazine 1.65 mg",
  "Glycerol (74.63%)",
  "Spirulina 500 mg",
  "- Chlorpheniramine Maleat- Guaifenesin- Noscapine- Paracetamol- Phenylpropanolamine Hydrocloride",
  "Hi Calcium",
  "NIACINAMIDE (VITAMIN B3) : Membantu mencerahkan",
  "Chlorpheniramine maleat 4 mg",
  "Equiseti Herba 1 g",
  "Cyclic & polymeric siloxanes",
  "Gypsum fibrosum 450mg",
  "Per 5 ml : Curcuminoid 2 mg",
  "Kurma",
  "Ekstrak ginkgo-Biloba 40 mg",
  "Setiap tablet mengandung: Ca Phosphate 333.34 mg",
  "dehydrated poultry protein",
  "Eucalyptus Oil",
  "Omega-3 Fatty Acids",
  "Paracetamol 500 mg",
  "Aqua",
  "Methyl salicylate 30%",
  "Sonchi Folium 75 mg",
  "Feracrylum",
  "Dextromethorphan HBr 15 mg",
  "Ondansetron HCl dihydrate 4 mg",
  "Laktosa",
  "Tranexamic acid 500 mg",
  "Cholecalciferol 2000 IU",
  "N-Acetylcysteine 600 mg",
  "Dehydrated poultry protein",
  "Papaya fruit powder 30 mg",
  "Tetracycline HCl 500 mg",
  "guafinesin",
  "Chloramphenicol 0.5 %",
  "Herbal Tribulus Terrestris",
  "Sodium palmate",
  "Susu skim bubuk",
  "Chlorpheniramini maleat 4 mg",
  "Clobetasol propionate 0.5 mg",
  "Aqua Sodium Laureth Sodium Chloride Cocamide DEA Phenoxyethanol Sodium Benzoate Parfum PEG250 Distearate Citric Acid Benzophenone4 Disodium EDTA PEG40 Hydrogenated Castor Oil Butyl Methoxydibenzoylmethane Citrus Sinensis Fruit Water Butylene Glycol Terminalia Ferdinandiana Fruit Extract Alcohol Denat Limonene Hexyl Cinnamal Linalool",
  "gentamicin",
  "Pemanis alami sorbitol",
  "Omega-3 Marine Triglycerides (1000 mg)/ EPA (Eicosapentaenoic Acid) 180 mg/ DHA (Docosahexaenoic Acid) 120 mg",
  "Zingiberis Rhizoma 0.743",
  "Minyak Kayu Putih (Cajuput oil)",
  "Ethylhexyl-Methoxycinnamate",
  "Vitamin C (Calcium ascorbate) 300 mg",
  "Per-kapsul: Folic acid 800 mcg",
  "Cefadroxil Mohohydrate 250 mg/5 ml",
  "Per 5 mL: Amoxicillin 125 mg",
  "Setiap Kapsul mengandung: Cholecalciferol 1000",
  "Trimetoprim 160 mg",
  "kandungan DHA",
  "Ibuprofen 100 mg/ 5ml",
  "Per 5 mL : Magnesium Hydroxide 325 mg",
  "Sumatriptan succinate 100 mg",
  "Sennae Folium Extract : 27.5 mgCentellae Herba Extract : 82.5 mgCurcumae Rhizoma Extract : 165.0 mgSericocalycis Folium Extract : 137.5 mgColei atropurpurei Folium Extract : 137.5 mg",
  "Carbamide carbonyl diamide",
  "Retinoic acid 0.05%",
  "Oleum Eucalyptus",
  "Acetylsalicylic acid 80 mg",
  "Omega-3 Fatty Acids 250 mg (EPA 100 mg",
  "Absorbent sheet Non woven Backsheet Indtvidual film Hotmelt Release paper Elastic yarn",
  "Polyaminopropyl biguanide 0",
  "Pseudoefedrin HCl 30mg",
  "Ekstrak billberry fructus 100 mg ( terstandarisasi 32% Anthocyanidin )",
  "Zingiberis officinalis Rhizoma 7.336 g",
  "Multivitamin",
  "menthol crystal pure herbal yang di extrak dari corn mint dan pappermint.",
  "EPA: 18% (180 MG",
  "NaCI 9 g",
  "Naftidrofuryl oxalate",
  "Oleum Cajuputi 100%",
  "Aqua",
  "Granisetron HCl 1 mg",
  "Gentamicin 0.1%",
  "Glucosamine HCI 250 mg",
  "Risperidone",
  "Echinacea purpurea herba dry extract 50 mg. Zingiberis officinale var rubrum rhizome extract 25 mg. Bahan tambahan: Sorbitol",
  "Derma Angel Acne Patch Day: Hidrocoloid ACNOL LOTION 10 ML: Allantoin 0.20%",
  "Lidocaine HCl 2%",
  "Glucosamine Sulfate 1000 mg",
  "Essential phospholipide 300 mg",
  "Methyl Salicylate 28%",
  "vegetable protein isolate*",
  "Cereal",
  "Kaolin 986",
  "vitamin C",
  "Tiap 5 ml mengandung: - Oxomemazine Hydrochloride setara dengan Oxomemazine 1",
  "Insulin (various types)",
  "Leucoselect phytosome 25 mg",
  "Salmeterol 25 mcg",
  "Domperidone 5 mg/5 ml",
  "Mineral Water",
  "Tiap 5 ml mengandung: Guaifenesin 50 mg",
  "Tiap kapsul mengandung:UC-II�(Undenatured Type II Collagen) 40 mgMSM(Methylsulfonylmethane) 300 mgBSE(Boswellia Serrata Extract ) 100 mg",
  "Piracetam",
  "Cinnarizine",
  "Vitamin A",
  "Tiap Gram Mengandung Gentamicin Sulfate Setara Dengan 1 Mg Gentamicin Base.",
  "Garcinia cambogia 300 mg",
  "Acidum Salicylicum",
  "purified arctic cod liver oil",
  "Mahkota dewa",
  "water",
  "Rifampicin 75 mg",
  "Spirulina Powder (Organic) 500 mg",
  "Ekstrak buah goji berry",
  "Tiap 5 ml: Ibuprofen 200 mg",
  "Paracetamol 250 mg",
  "Ibuprofen 125 mg",
  "Ezetimibe 10 mg",
  "Dequalinium Chloride 0.25 mg",
  "Fluocinolone acetonide 0.025%",
  "Alumunium Hydroxide 200 mg",
  "Tretinoin 0.1 %",
  "Sukrosa",
  "Sweet cherry fruit ( Prunus serotina fructus) 200 mg",
  "Oleum Cajuputi",
  "Valacyclovir HCl 500 mg",
  "Tiap 1 ml mengandung: Ciprofloxacin 3 mg",
  "AQUA",
  "Purified water",
  "Vitamin A 5000IU (500 RE). Vitamin B1 6.1mg. Vitamin B2 8.5mg. Vitamin B3 60mg. Vitamin B5 20mg. Vitamin B6 8mg. asam folat 200 mcg. Vitamin B12 10 mcg. Vitamin C 180mg. Vitamin D3 400IU (10 mcg). Vitamin E 20IU (13.4mg). Biotin 25 mcg. Kolin 10.3mg",
  "Allylestrenol 5 mg",
  "Glychirrhizae succus 166",
  "Madu",
  "Baclofen",
  "AQUA/WATER",
  "Amoxicillin 500 mg",
  "Telmisartan 80 mg",
  "58% Water Content",
  "desloratadine",
  "Ground corn",
  "Isoflavone 50 mg (termasuk genistine & diazine dr soy isoflavone 40% 125 mg)",
  "Naproxen Sodium 500 mg",
  "Azithromycin 200 mg/5 ml",
  "Mometasone furoate 0",
  "Chicken",
  "Tiap gram mengandung 1 mg Triamcinolone acetonide",
  "Tiap 5 ml mengandung :Pseudoephedrine HCl 15 mg",
  "Clindamycin phosphate 1%",
  "Cinnamomum Burmanni Cortex Ekstrak 50 mg",
  "trimethoprim 40 mg + sulfamethoxazole 200 mg",
  "Per takaran saji ( 58g / 4 sendok takar ) : Total fat 8g",
  "Natrium klorida",
  "Tiap 1 Kaplet mengandung: Metformin Hcl 850 mg",
  "Carica Papaya (Papaya) fruit extract",
  "Thymus vulgaris herba",
  "Minosep Obat Kumur 0.2% 150 ml (Merah): Chlorhexidine gluconate 0.2%Cheng Sie Lung Hau Feng Yao San 1.2 G: Glycyrrhizae Glabra Radix 480 mg",
  "Empagliflozin 25 mg",
  "Asam Askorbat 400 mg",
  "Psyllium Seed Husk (Plantago ovata) 2000 mg ActiZyme Proprietary Enzyme Blend (Total Enzymatic Activity > 4000 [Combined Units]) 100 mg Cellulase",
  "Losartan",
  "Natural Fish oil mengandung DHA 75 mg",
  "Per gram : Miconazole nitrate 20 mg",
  "Per-5 mL : Paracetamol 130 mg",
  "Beta-carotene 10000 IU",
  "Beta karoten 10000 IU",
  "Ubidecarenone 30 mg",
  "Soft cotton",
  "Omega-3 Fatty Acids 1000 mg",
  "Per 5 ml : Ambroxol HCl 15 mg",
  "Candesartan 8 mg",
  "60% Water content",
  "Setiap tablet Combantrin 125 mg mengandung Pirantel Pamoat setara dengan pirantel base 125 mg.",
  "Minuman penurun kolesterol yang mengandung: susu",
  "Susu sapi",
  "Diphenhydramine HCl 5 mg",
  "Setiap ml mengandung: Insulin Glargine 100 IU",
  "Vitacimin mengandung : Acidum ascorbicum (Vitamin C) 250 mg dan Natrii ascorbas 281.25 mg.",
  "Tiap tablet o-dis (tablet cepat larut) mengandung Citicoline 500 mg",
  "Amoni Fructus (kapulaga)",
  "Fipronil 0",
  "Water",
  "Per 5 mL : Sodium Fe EDTA 115.4 mg setara dengan Fe elemen 15 mg.",
  "Hyaluronic Acid 100 mg",
  "Triamcinolone acetonide 0.1%",
  "Setiap orally disintegrating tablet mengandung rimegepant sulfate",
  "Beta-carotene 5000 IU",
  "Piperazine Citrate : 1",
  "Dapaglifozin Propenadiol 10 mg",
  "Pure mom nipple cream mengandung zat aktif yaitu provitamin B5 (D-panthenol)",
  "Bahan/Material : Hema",
  "Lamb meal",
  "Saxagliptin 5 mg",
  "Ibuprofen 100 mg",
  "Tiap gram mengandung:Ibuprofen 50 mg.",
  "Dehydrated poultry protein",
  "Dehydrated poultry protein*",
  "Metronidazole 125 mg",
  "Water",
  "Tiap kapsul mengandung: Erdostein 300 mg.",
  "Natrium diklofenac",
  "Mexoryl 400: Proteksi dari Ultra Long - UVA",
  "Paracetamol 160 mg/5 ml",
  "Pentoxifylline 400 mg",
  "Tiap kapsul 300mg mengandung: extractrum Apii graveolentis herba 46 mg",
  "Per sachet D-ribose 5 g",
  "Oleum foeniculli",
  "Tiap gram salep mengandung Kloramfenikol 1% dan Polimiksin B sulfat 5000 IU",
  "Konsentrat umbi kering Allium sativum (bawang putih) dry bulb concentrate setara dengan umbi segar 30 mg. Serbuk tanaman Petroselinum crispum (peterseli) 20 mg.",
  "Sonchus arvensis Folium : 22.5 mgSericocalyx crispus Folium : 180mgOrthosiphon stamineus Folium : 22.5 mg",
  "Vitamin B1 1 mg",
  "Hydroquinon",
  "Tiap gram mengandung:Diclofenac Diethylamine 11.6 mg setara dengan Diclofenac Sodium 10 mg.",
  "Gentamicin sulfate 0.1 %",
  "Per 5 ml: Pseudoephedrine HCl 15 mg",
  "L-lysine 50 mg",
  "Griseofulvin (micronized) 500 mg",
  "Cushion dengan ketebalan 4mm",
  "Susu bubuk skim (28%)",
  "Cajuput Oil 97%Natural Rhodinol 3%",
  "Balsamum Peruvianum",
  "Oleum Cocos (Virgin Coconut Oil) 1000 mg",
  "Dexamethasone 0.5 mg",
  "dex-ctm",
  "Vitamin A Palmitate 10 mg (1000 IU)",
  "Etoricoxib 60 mg",
  "Nigellae Sativa",
  "Docusate Sodium 50 mg.",
  "Konsentrat umbi kering Allium Sativum (bawang putih) setara dengan konsentrasi umbi kering 30 mg",
  "Clobetasol 0",
  "Ethambutol / Etambutol Hcl.",
  "Curcuminoid 20 Mg",
  "Aqua",
  "Per 5 mL: Dextromethorphan HBr 5 mg",
  "Water",
  "Levofloxacin 500 mg",
  "Iron 20 mg",
  "Morinda Citrifolia Fructus 250 Mg",
  "Bisoprolol fumarate 10 mg",
  "Broad Spectrum Sunscreen: SPF 30 dan PA+++",
  "dehydrated poultry protein",
  "Cyclopentasiloxane Cyclotetrasiloxane Dimethiconol Fragrance Tocopheryl Acetate Simmondsia Chinensis Seed Oil Polysilicone-15 Soybean (Glycine Soja) Oil Panthenyl Ethyl Ether Retinyl Palmitate Argania Spinosa Oil Ascorbyl Palmitate Dimensi Produk : 60 x 60 x 107 mm",
  "Diflucortolone valerate 0.1 %",
  "Vitamin E (d-alfa-tocopherol) 400IU",
  "Vitamin C",
  "Tiap tablet mengandung: Amlodipine Besylate 5 mg",
  "Chamomilla Recutita Flower Extract",
  "Tiap tablet salut selaput mengandung Loperamide 2 mg",
  "L-Menthol 310mg",
  "Sodium Bicarbonate (Natrium Bikarbonat)",
  "Per 5 mL : Amoxicillin 250 mg",
  "Ekstrak Red Ginseng 55.5 mg",
  "Setiap kapsul mengandung: L-Gluthatione reduced 500 mg",
  "Metoclopramide HCl",
  "Squalene 480mg",
  "meat and animal derivatives",
  "Aqua",
  "Kalsium glukonat",
  "Acidic colloidal carbomer",
  "Lansoprazole",
  "Citronella",
  "Natural Astaxanthin 6 mg (AstaREAL 50FC 120 mg)",
  "Aloe Vera",
  "Vitamin C 250 mg dan Ekstrak Jahe Merah 50 mg.",
  "madu",
  "ekstrak Morinda Citrifolia 500 mg.",
  "Tiap 5 ml mengandung : Salbutamol sulfate 2 mg",
  "Kloramfenikol 2 %",
  "Vitamin E 400IU",
  "Febuxostat 40 mg",
  "Montelukast Sodium 11.18 mg",
  "Ossein Hydroxyapatite Compound (OHC) 800 mg (Ca 178 mg dan phospor 82 mg",
  "Famotidine 20 mg",
  "Menthol 20%",
  "Meat and animal derivatives",
  "Clindamycin HCL setara dengan Clindamycin 150 mg",
  "Aqua Cetearyl Alcohol Dimethicone Dimethiconol Cetyl Esters Amodimethicone Cyclotetrasiloxane Trideceth-12 Cetrimonium Chloride Cyclopentasiloxane Sodium Benzoate Dimethyl Palmitamine Steartrimonium Chloride Isopropyl Alcohol Potato Starch Modified Fragrance Isostearic Acid AMP-Isostearoyl Wheat/Corn/Soy Amino Acids Aminomethyl Propanol Phenoxyethanol Benzyl Alcohol Lactic Acid Panthenol Aleurites Mollucana Seed Oil Soybean (Glycine Soja) Oil Aloe Barbadensis Leaf Extract Ascorbyl Palmitate Tocopheryl Acetate Retinyl Palmitate",
  "alkohol 70 %",
  "Tiap tablet mengandung:- Fish Collagen Powder (Collactive) 500 mg. - Pomegranate (Punica granatum fructus) Powder Extract (Viqua) 62.5 mg.",
  "rice",
  "Dextromethorphan HBr 5 mg",
  "Propyl paraben",
  "Esktrak folium orthosiphon stamineus 18 mg",
  "Water (Aqua)",
  "Tiap mL larutan isotonik steril mengandung: Tetrahydrozoline HCl 0.05% b/v",
  "Ekstrak daun kelor 400 mg.",
  "Susu bubuk skim",
  "Hydroxychloroquine Sulfate 200 mg",
  "Metampiron 250 mg",
  "Sucralfate",
  "Vitamin B12 50 mcg",
  "Ammonium Chloride",
  "Aqua",
  "Per 5 mL : Kotrimoksazol (Sulfametoksazol 200 mg",
  "Zink picolinate 50 mg",
  "Thyme powder extract 10 mg",
  "Placenta extract 10% dan Neomycin sulfate 0.5%.",
  "Plucheae Folium Extract : 110 mgCurcumae Rhizoma Extract : 110 mgAndrographidis Herba Extract : 110 mgTinosporae Caulis Extract : 220 mg",
  "Sophora root ekstrak",
  "Marine Protein 100 mg",
  "Gentamicin sulphate",
  "Atorvastatin 20 mg",
  "Flumethrin 5.9%",
  "Tiap 5 ml mengandung: Amoxicillin Trihydrate 125mg",
  "Ekstrak Echinacea 500 mg",
  "Siraitiae Grosvenorii Fructus 100 mgEriobotryae Japonica Folium 100 mgTerminalia Chebulae Fructus 100 mgChebulae Fructus Immaturus 50 mgPlatycodonis Grandiflorum Radix 50 mgPrunus Armeniacae Semen Amarum 50 mgCitri Exocarpium Rubrum 50 mgAdenophorae Tetraphylla Radix 50 mgStemonae Sessilifolia Radix 50 mgHouttuynia Cordata Herba 50 mgMorus Alba Folium 50 mgGlycyrrhizae Uralensis Radix et Rhizoma 50 mgI-Menthol (Menthahaplo-calyx) 1.75 mgEucalyptus Oil 6.25 mgMel 420 mgMalt Syrup 420 mgGlucose Syrup 420 mgWhite Granulated Sugar 1000 mgAnhydrous Citric Acid 8 mgAlmond Essence 10 mgCaramel Pigment (E-150) 2 mgTalcum 2 mg",
  "Per 5 ml : Echinacea 250 mg",
  "Krim Pewarna: WATER",
  "Water",
  "Setiap kaplet mengandung Vitamin A 5000 IU",
  "Iodine Povidon",
  "Ibuprofen 100 mg/5 ml",
  "Cinamomum camphora Folium 248.4 mg",
  "Ondansetron 8 mg",
  "Tepung kedelai",
  "sukrosa",
  "Alkohol (Ethanol) 70%",
  "Myristic Acid",
  "AmLodipine Bestylate 5 mg & Valsartan 160 mg",
  "Tioconazole 1%",
  "Natural vitamin E 400 IU",
  "Policresulen 100 mg",
  "Per mL : Cefadroxil 150 mg",
  "Amlodipine 5 mg",
  "Tiap mL mengandung 15 mg Fe",
  "Glycyrrhizae succus",
  "Tiap 5 ml mengandung:Cetirizine Hydrochloride 5 mg",
  "Graptophyllum pictum extrak 14 mg",
  "Telmisartan 40 mg",
  "Per 5 mL : Curcuminoid 2 mg",
  "Chlorpheniramine Maleate 4 mg",
  "Pyridostigmine Br 60 mg",
  "Jintan hitam",
  "Acyclovir 200 mg",
  "Panadol Cold & Flu 10 Kaplet: Paracetamol 500 mg",
  "Tiap tablet mengandung Ester-C 320 mg yang setara dengan vitamin C 247",
  "Clindamycin / Klindamisin Hcl.",
  "Ciutrus sinens fructus extract 500 mg",
  "Empagliflozin 12",
  "Na Fluorescein",
  "Tranexamic",
  "Ekstrak bawang putih tunggal tiongkok",
  "Per-5 mL : Bromhexine HCl 4 mg",
  "Tiap tablet mengandung: Norethisterone 5 mg",
  "Per 5 ml : Phenolphthalein 55 mg",
  "Essential phospholipids 300 mg",
  "Losartan Potassium 50 mg",
  "Amoxycillin trihydrate 100 mg",
  "Per mL: Dexamethasone 1 mg",
  "IRON (AS IRON OXIDE)",
  "Mometasone furoate 1%",
  "Cairan isotonik steril yang mengandung Polyhexamthylene biguanide 1.6 ppm",
  "Rifampicin 150 mg",
  "Aqua Cetearyl Alcohol Dimethicone Dimethiconol Cetyl Esters Amodimethicone Cyclotetrasiloxane Trideceth-12 Cetrimonium Chloride Cyclopentasiloxane Sodium Benzoate Dimethyl Palmitamine Steartrimonium Chloride Isopropyl Alcohol Potato Starch Modified Fragrance Isostearic Acid AMP-Isostearoyl Wheat/Corn/Soy Amino Acids Aminomethyl Propanol Phenoxyethanol Methylparaben Propylparaben Lactic Acid Panthenol Simmondsia Chinensis Seed Oil Ascorbyl Palmitate Tocopheryl Acetate Retinyl Palmitate Soybean (Glycine Soja) Oil Dimensi Produk : 90 x 156 mm",
  "Pramipexole diHCl 0.375 mg",
  "Silybum Marianum dried extr.",
  "Foeniculi fructus (Minyak Adas) 10%",
  "Tripeptide",
  "Amlodipine Besylate 5 mg",
  "Enalapril",
  "Ibuprofen 20 mg",
  "Tepung terigu",
  "Perindopril Arginine 5 mg",
  "Tiap kapsul mengandung : Ekstrak jinten hitam (Nigela Sativa Semen Extract) 600 mg",
  "Hydrotalcite",
  "Tepung beras",
  "Levothyroxine Na 50 mcg",
  "Dried sea fish",
  "Tiap 5 ml mengandung Paracetamol 120 mg",
  "Madu",
  "Per 5 mL: Ampicillin Trihydrate 250 mg",
  "Neomycin sulfate 5 mg",
  "Per 5 mL : Diphenhydramine HCl 12.5 mg",
  "Tea Tree Oil & Salicylic Acid",
  "Water",
  "Sugar",
  "Pioglitazone HCl 15 mg",
  "Per 5 mL : Betamethasone 0",
  "Cimetidine 200 mg",
  "Tiap tablet salut selaput mengandung : Organic calcium from sea 1067 mg (mengandung Kalsium 363 mg)",
  "Tiap 5 ml mengandung : Paracetamol 160 mg",
  "Liraglutide 6 mg/ml",
  "Esomeprazole 40 mg",
  "Chlorhexidine gluconate 0.2%",
  "Perindopril Arginine 10 mg",
  "Setiap kapsul mengandung ekstrak bawang putih (Allii sativi Bulbus Extract) setara dengan 1",
  "Per 5 mL : Paracetamol 125 mg",
  "Glukosamin HCL 250 mg",
  "Cellulose Gum",
  "Aqua Sodium Laureth Sulfate Sodium Chloride Glycerin Cocamide DEA Cocamidopropyl Betaine Niacinamide Glycol Distearate Parfum StyreneAcrylates Copolymer Citric Acid Tetrasodium EDTA Cocoamide MEA Laureth10 Magnesium Nitrate Caprae Lac Powder Methylchloroisothiazolinone Propylene Glycol Magnesium Chloride Methylisothiazolinone Milk Protein Lactose Phenoxyethanol Lactic Acid Sodium Dehydroacetate Hexyl Cinnamal Limonene CI 19141",
  "Thiamphenicol / Tiamfenikol.",
  "Tiap 1 Kapsul Lunak mengandung:Niacinamide 15 mgBiotin 45 ugVitamin B1 Mononitrate 2.2 mgVitamin B2 (Riboflavin) 2.4 mgVitamin B6 (Pyridoxine HCL) 3.2 mgVitamin C 100 mgVitamin E (D-alfa-Tocopherol) 10 mgAsam Folat 200 ugVitamin D 5.0 ugKalsium Pantotenat 9.2 mgVitamin B12 (Cyanocobalamin) 6.0 ugBioflavonoid?- Hesperidin 10 mg- Enzymatically modified Rutin 25 mgBeta-Karoten 5400 ug",
  "Tiap 5ml mengandung: Paracetamol 120 mg",
  "Guaifenesin 50 mg",
  "Bepotastine besilate 10 mg",
  "Tiap 15 ml : Succus liquiritiae 500 mg",
  "Montelukast 4 mg",
  "Echinacea purpurea extract (fresh pressed juice) 500 mg",
  "5% Niacinamide",
  "Tiap Tablet mengandung : - Cyanocobalamin- Metamizole Sodium Monohydrate- Pyridoxine Hydrocloride- Thiamine Nitrate",
  "Guaifenesin 100 mg",
  "Organic Flaxseed Oil 1000 mg",
  "Bismuth Subsalicylate 125 mg",
  "Bromhexine HCl 8 mg",
  "D",
  "WaterAqua Lauric Acid Potassium Hydroxide Myristic Acid Glycol Distearate FragranceParfum Palmitic Acid Laureth4 Sodium Laureth Sulfate Hydroxyethylcellulose Etidronic Acid",
  "Natrium Diklofenak 50 mg",
  "Tiap sendok (5 ml) mengandung: Metronidazol benzoate yang setara dengab 125 mg Metronidazole",
  "Moisture 85",
  "diperkaya kandungan CHE",
  "Guaifenesin",
  "Vitamin B1 100 mg",
  "Lutein 5% 6 mg",
  "Retrofracti fructus 245 mg",
  "DL-3-methyl-2-oxo-valeric acid 67 mg",
  "Ketoconazole 1%",
  "Tiap 5 ml mengandung: Ibuprofen 200 mg",
  "Radix Saposhnikoviae 220 mg",
  "Bubuk Whey Terdemineralisasi",
  "Gom Arab",
  "Echinacea purpurea dry herb extract 500 mg",
  "Betametasone",
  "Asam folat 1 mg",
  "Nano Coenzyme Q-10 (Ubiquinone)",
  "Amlodipine 10 mg",
  "Bisoprolol Hemifumarate 2.5 mg",
  "Alcohol",
  "Sitagliptin 50 mg",
  "Cinnarizine 25 mg",
  "Ekstrak Kunyit 4.68 g",
  "Vitamin B1",
  "Dulaglutide 0.75 mg/ 0.5 ml",
  "Polysiloxanes",
  "Aqua",
  "Fluocinolone acetonide 0.025%",
  "Eucalyptus Oil 99.75%",
  "Loperamide HCl 2 mg",
  "Lansoprazole 15 mg",
  "Stachytarpheta Mutabilis Folium 30 mg",
  "Cholecalciferol 5000 IU setara dengan Cholecalciferol (Vitamin D3) 125 mcg",
  "Natural Astaxanthin 12 mg",
  "Nabumetone 500 mg",
  "Setiap 5 ml mengandung Vitamin D3 400 IU",
  "Fipronyl",
  "Tretinoin (Retinoic Acid) 0.05%",
  "Per 5 mL : Vit.A 5000 IU",
  "Tiap ml mengandung:Cetirizine HCl 10 mg",
  "Water Homosalate Ethylhexyl Methoxycinnamate BHT Ethyhexyl Salicylate Titanium Dioxide Trimethoxycaprylylsilane Alcohol Denat Distarch Phospate Cetearyl Alcohol PEG 40 Castor Oil Sodium Cetearyl Sulfate Benzophenone3 Oxybenzone BisEthylhexyloxyphenol Methoxyphenyl Triazine Butyl Methoxydibenzolymethane Phenylbenzimidazole Sulfonic Acid Dimethicone Glycerin Trisodium EDTA Glyceryl Stearate SE Cetyl Alcohol Ethylhexylglycerin Hydrogenated CocoGlycerides Tocopheryl Acetate Xanthan Gum Phenoxyethanol Sodium hydroxide Methylparaben Propylparaben Ethylparaben Parfum",
  "Tiap 5 ml mengandung :Ibuprofen 200 mg",
  "L-glutamine 250 mg",
  "Daun Wungu (Graptophylli Folium)",
  "Tiap kapsul mengandung : Standardized Lingzhi (Ganoderma lucidum) Extract 150 mg",
  "Tpe Dengan Ketebalan 003cm",
  "Vitamin D 400 IU",
  "Pravastatin Na 20 mg",
  "Per 5 mL : Sucralfate 500 mg",
  "Adapalen 0.1%",
  "Per 5 mL: Erythromycin strearate 200 mg",
  "Metil salisilat 30%",
  "Curcuma xanthorrhiza extract 52 mg",
  "Trioctyldodecyl Citrate",
  "Per-5 mL : Valproic acid 250 mg",
  "Tiap gram mengandung : Hidroquinon USP 4 %",
  "Tiap tablet mengandung Valsartan 80 mg",
  "Metronidazole 500 mg",
  "Mineral oil",
  "Paracetamol 500 mg",
  "Vit.E 300 mg",
  "Ammonium Chloride",
  "Pyrazinamide 500 mg",
  "Per 5 ml mengandung: Piracetam 500 mg",
  "Mel depuratum 16 g",
  "Dextromethorphan",
  "Ekstrak Schizandrae Fructus 135 mg",
  "Tiap 1 sendok takar (5 ml) mengandung:Diphenhydramine HCl 13.5 mg",
  "Consumer Goods",
  "Ondansentron 4 mg",
  "organic oat",
  "Everolimus 0.5 mg",
  "Ampicillin 500 mg",
  "Per 5 mL : Curcuminoid 2 mg",
  "• Aqua (water)• Glyceryl Stearate• Hydrogenated Coco-Glycerides• Petrolatum• Cyclopentasiloxane• Cetyl Palmitat• Laureth-23• 1",
  "Jinten hitam",
  "Tiap g powder mengandung: Neomycin sulfate 5 mg",
  "Bakteriostatik",
  "asam folat 400 mcg",
  "Tiap 5 ml mengandung Echinacea Purpurea extract 250 mg",
  "Fenugreek seed (Trigonella Foenum-graecum semen) extrak 600 mg",
  "DLBS5055",
  "Maize",
  "Prekusor",
  "Purified deep sea fish oil (from anchovies and sardines)",
  "Tiap kapsul mengandung Fenofibrate 200 mg",
  "Tiap tablet mengandung: L- Arginine 100 mg",
  "Fish oil (natural) 1034 mg Mengandung omega-3: 518 mg Eicosapentaenoic acid (EPA) 310.8 mg Docosahexaenoic acid (DHA) 207.2 mg Bahan tambahan : Gelatin (bovine hide)",
  "Vitamin E 30 I.U Tiamin HCl (B1) 100 mg Piridoksin HCl (B6) 50 mg Sianokonolamin (B12) 100 mcg K-l-aspartat 100 mg Mg-I-aspartat 100 mg",
  "Rice",
  "Setiap kapsul mengandung ekstrak: Curcumae Xanthorriza Rhizoma Extract (Temulawak) 160 mg",
  "Cyclobenzaprine",
  "Fe fumarate 300mg",
  "maltodektrin",
  "Bisoprolol fumarate 5 mg",
  "Dequalinium chloride 10 mg",
  "Levonorgestrel 0.15 mg",
  "Vit.A 3000 IU",
  "Oleum citronellae minyak sereh 2.1%",
  "Evodiae Leptae Herba",
  "Dexketoprofen trometamol 25 mg",
  "Mekobalamin 500 mcg",
  "Cisapride 5 mg",
  "Calcium Lactate100 mg",
  "Andrographis paniculata herba extract 80 mg",
  "Methylprednisolone 16 mg.",
  "Vitamin K",
  "Per 5 mL Diphenhydramine HCl 12.5 mg",
  "Per gram : Eucalyptol 10%",
  "Vitamin C Calsium Ascorbate 500 mg Citrus Bioflavonoid Complex 200 mg Calcium Calcium Carbonate 50 mg",
  "Ekstrak Gingseng & Olive Oil",
  "Mometasone furoate",
  "Setiap tablet kunyah mengandung:Magnesium Hydroxide 200 mgAlumunium Hydroxide gel kering (dried gel) 200 mgSimethicone 20 mg",
  "Per mL : Fe polymaltose complex 23.53 mg (setara elemental Fe 8 mg)",
  "Vegetable fibres",
  "Aqua (Water)",
  "Vitamin C 1 mg",
  "Metformin HCl 850 mg",
  "Tiap ml mengandung :Ambroxol 15 mg",
  "Levocetirizine Dihydrochloride 5 mg",
  "89% plasmolysed herbal yeast11% Bahan pengikat Natural (Cellulose",
  "Water",
  "Zinc Sulfate",
  "Ampicillin trihydrate 500 mg",
  "Setiap Tablet Mengandung : Vitamin B1 10 mg",
  "Tiap 5 ml mengandung :Paracetamol 160 mg",
  "Tiap kaplet mengandung Fe glukonat 250 mg",
  "Lumbricus Rubellus 180 mg",
  "Fluocortolone pivalate 1 mg",
  "Methyl Salicylate",
  "Gentamicin sulphate 0.1%",
  "Flourometholone",
  "Vitamin C lepas berkala 500 mg",
  "Tiap tube mengandung Selamectin 60 mg dalam 0",
  "Tetrahydrozoline HCl 0.05%",
  "Colchicine",
  "Chloramphenicol 0.5%",
  "Psyllium Husk",
  "Per 5 ml sirup mengandung Vit A 2",
  "Pioglitazone HCl 30 mg",
  "Asam 3-metil-2-oxovalerat 67 mg",
  "Ekstrak lumbricus rubellus 250 mg",
  "Hansaplast Antiseptik Pembersih Luka 40 ml: 0.04% Polihexanide (PHMB) dan 0.1% Decyl Glucoside Tenside dalam Larutan Ringer.Betadine 10% Salep 5 g: Povidone Iodine 10%.",
  "Habbatussauda",
  "dehydrated poultry protein",
  "Ekstrak daun kelor 500 mg.",
  "Per 5 mL : Ampicillin 125 mg",
  "Triprolidine HCl 2",
  "Ekstrak Temulawak 3.8 mg",
  "Fe fumarate 90 mg",
  "Allopurinol 300 mg",
  "Fe (III) hydroxide polymaltose complex setara dengan elemental Fe 50mg",
  "Bahan/Material : Hema",
  "Salbutamol Sulphate",
  "Desloratadine",
  "Aqua",
  "Silicone dan Polypropylene",
  "minyak JASMINE",
  "Tiap 5 mL mengandung : Procaterol 25 mcg",
  "Adenosine Triphosphate",
  "Aqua",
  "Ethynilestradiol 0",
  "Diphenhidramine HCl 25 mg",
  "Budesonide",
  "Temulawak Organik",
  "Tiap tablet mengandung 250 mg ekstrak echinacea purpurea",
  "Metoclopramide 10 mg",
  "Progesterone 400 mg",
  "Setiap tablet mengandung: Vitamin C 500 mg.",
  "Setiap tablet mengandung:Vitamin C 500 mg",
  "bahan 100% katun dengan kerapatan benang lebih tinggi.",
  "Losartan 50 mg",
  "Amino Blend (Micronized Taurine",
  "Tiap kapsul mengandung: Fish Oil 1000 mg",
  "Mirabegron 50 mg",
  "Vit.A 4000 IU",
  "Madu",
  "Desonide",
  "Per ml : Cetirizine 10 mg",
  "Per gram : Deksametason 0.1%",
  "Dehydrated poultry protein",
  "Atorvastatin Calcium 10 mg",
  "Citicoline Na 500 mg",
  "Echinacea extr. (EFLA 894) 250 mg",
  "Ferro fumarate 90 mg",
  "Rice",
  "Tiap sendok takar (5 ml) mengandung Cetirizine Hydrochloride 5 mg",
  "Aqua",
  "Per 5 mL : Domperidone 5 mg",
  "Curcuma longa rhizome extr (Curcuminoid 95%) 150 mg",
  "Sorbitol",
  "Ofloxacin 3 mg/ml",
  "Ferrous Fumarate 60 mg",
  "hidrokortison asetat 28 mg",
  "Piracetam 400 mg",
  "vitamin E beads pomegranate seed oil",
  "Chloramphenicol 20 mg",
  "Menthol 100%",
  "Madu hutan 266 g",
  "Per-5 ml : Paracetamol 120 mg",
  "Tiap 5 mL mengandung 15 mg Fe",
  "Tiap tablet mengandung : Dextromethorphan HBr 15 mg",
  "Minyak Zaitun Extra Virgin Extra Virgin Olive Oil",
  "Per 5 mL : Triprolidine HCl 1.25 mg",
  "Per gram : Asam fusidat 20 mg",
  "Methyl Salicilate 4",
  "Tiap g Mengandung: Menthol 70 mg",
  "Tuna",
  "Minocycline HCI 100 mg",
  "COLCHICINE 0.5 MG",
  "Aqua Isopropyl Alcohol Fragrance Triticum Vulgare Germ Oil PEG40 Hydrogenated Castor Oil Piroctone Olamine Sodium Salicylate Propylene Glycol DPanthenol Citric Acid Menthol Camphor Tocopheryl Acetate Lysine Methionine Chamomilla Recutita Flower Extract Glucose Glycine Linoleic Acid Retinyl Palmitate Arginine Leucine Histidine Proline Valine Lactic Acid Serine Sodium Benzoate CI 42090 Urtica Dioica Extract Betula Alba Leaf Extract Equisetum Arvense Extract Capric Acid Potassium Sorbate Caramel Tartaric Acid CI 17200 Biotin Riboflavin",
  "Fusidic acid",
  "Ekstrak Sambiloto (Andrographis paniculata) 500 mg.",
  "Per Gram: Zn bacitracin 500 iu",
  "Vit A 6",
  "Mineral oil",
  "Calamin 10%",
  "Vitamin B1 100 mg",
  "Corn",
  "Paracetamol 650 mg",
  "Thiamphenicol 500 mg",
  "Tiap 5 ml mengandung : Vitamin A 2400 iu",
  "asam tranexamed",
  "Tiap 5 ml mengandung: Ibuprofen 100 mg.",
  "Co-enzym Q 10(ubidecarenone) 100mg",
  "Xylitol",
  "Cefixime",
  "Harpagophytum procumbens extract 250 mg",
  "Tiap 5 ml mengandung :Ibuprofen 200 mg",
  "Poultry viscera flour",
  "Coral Ca 500 mg",
  "Ekstrak tanaman tradisional seperti Majakani",
  "Tiap 1 mL mengandung:- Polymyxin B sulfate 10.000 IU.- Neomycin sulfate 3.390 IU.- Betamethasone base 1 mg.- Lidocaine hydrochloride 40 mg.",
  "Ester-C 320 mg yang setara dengan vitamin C 250 mg",
  "Hydrocolloid Dresingtanpa bahan kimia",
  "Ginkgo-Biloba extract (EGb761) 80 mg",
  "Methisoprinol 500 mg",
  "Methampyrone 250mg",
  "Setiap tablet effervescent mengandung: Vitamin C 1000 mg dan Zinc 10 mg.",
  "Clopidogrel",
  "Ruxolitinib Phosphate 15 mg",
  "Ramosetron Hcl",
  "Dextromethorphan HBr 15 mg",
  "Tiap 5 ml mengandung: Sucralfate 500 mg",
  "Tiap 15 ml mengandung: Guaifenesin 150 mg Dextromethorphan HBr 15 mg Bromhexine HCl 10 mg",
  "Lechitin murni (PePeCe 95) 150 mg",
  "Curcumae domesticae Rhizoma 45 mg",
  "Crizotinib 250 mg",
  "Lactobacillus helveticus Rosell-52 and Lactobacillus rhamnosus Rosell-11 2.000.000.000 CFU",
  "Tiap tablet mengandung Amlodipine Bestylate 10 mg",
  "minyak zaitun",
  "Bahan/Material : Silicon Hydrogel",
  "Pemanis alami sorbitol & eritritol",
  "Per mL : Cefadroxil monohydrate 125 mg",
  "Imatinib Mesilate 400 mg",
  "Chromium 200 mcg",
  "Per 5 mL : Amoxycillin 125 mg dan clavulanic acid 31.25 mg",
  "Ekstrak Kunir Putih (Curcumae manggae Rhizoma) 500 mg",
  "Guazumae Folium 150 mg",
  "Amylase",
  "Dexamethasone 0.5 mg",
  "Diosmin 450 mg",
  "Vitamin E 300 IU",
  "Latanoprost 0.05 mg",
  "Tiap kapsul lunak mengandung: Ubiquinol 100 mgL-Carnitine Fumarate 400 mgVitamin E 100 IUAsam Folat 800 mcg",
  "Water",
  "Inositol",
  "Tiap tablet mengandung:Guaifenesin 100 mgDextromethorphan HBr 5 mgChlorpeniramine maleate 2 mg",
  "Hydrocortisone acetate 5 mg dan Chloramphenicol 2 mg",
  "Ruxolitinib Phosphate 5 mg",
  "Pirasetam 1200 mg",
  "rice",
  "Ekstrak Phaleria macrocarpa (Mahkota Dewa) 120mg",
  "Desoksimetasone 0.25 %",
  "Mengandung:- Ekstrak Vitis vinifera (biji anggur) setara dengan biji kering terstandar yang mengandung procyanidin 8.5 mg: 1.2 g (1200 mg).- Ekstrak Silybum marianum (Milk Thistle) setara dengan buah kering yang terstandardisasi untuk mengandung flavanolignan 8.4 mg : 700 mg.- Selenomethionin (Selenium 13 mcg): 32.2 mcg.- Beta-karoten (sumber alami): 3 mg.- Vitamin B1 (Tiamin nitrat): 10 mg.- Vitamin B5 (Asam Pantotenat dar kalsium pantotenat 55 mg): 49.6 mg.- Vitamin B6 (Piridoksin hidrklorida): 25 mg.- Vitamin B12 (Sianokobalamin): 50 mcg.- Vitamin C (dari asam askorbat 150 mg and dan kalsium askorbat 121 mg): 250 mg.- Vitamin E alami (d-alfa-tokoferol 67.1 mg): 100 IU.- Kelasi asam amino Zinc amino acid (Zinc 5 mg): 25 mg.- Asam folat: 250 mcg.",
  "Per-kali semprot/puff mengandung : Salbutamol Sulfate 100 mcg.",
  "Fe gluconate 250 mg (setara elemental Fe 30 mg)",
  "Per ml: Natrium klorida 6",
  "Tiap gram gel mengandungMometasone furoate 1 mg",
  "Water",
  "Silybin-Phospholipid 120 mmg",
  "Per 5 mL : Dextromethorphan HBr 7.5 mg",
  "Povidone iodine 10%",
  "Hyoscine-N-butylbromide 10 mg",
  "Eucalyptus Oil 100 %",
  "Hydrocortisone acetate 1 %",
  "Amoxicillin trihydrate 250 mg",
  "Tiap pouch mengandung: 100% biji melinjo",
  "chlorpheniramin maleat",
  "Tiap tablet kunyah mengandung :Vitamin A (Fish Liver Oil) 2500 IU",
  "Aqua",
  "Bahan/Material : Etafilcon A",
  "Nifedipine 10 mg",
  "Cetirizine HCl 10 mg/ml",
  "Duloxetine",
  "Per 15 ml mengandung ekstrak setara : Akar kayu manis 200 mg",
  "Deltamethrin",
  "cimetidine",
  "Piroxicam 0.5%",
  "Dimenhydrinate 50 mg",
  "Colistin Sulfate (Polymyxin E Sulphate) 250000 IU",
  "Famotidine 10 mg",
  "Centellae Herba 78.75 mg",
  "Linagliptin 2.5 mg",
  "Emibion 10 Kapsul",
  "Vicee 500 Rasa Strawberry 50 Strip (2 Tablet/Strip) - Hemat Borongan",
  "Blackmores Ginkgo Action / Ginkgo Recall 30 Tablet",
  "Natures Plus RX Fiberific 120 Kapsul",
  "Cussons Baby Powder Mild & Gentle 350 g",
  "Qcef 500 mg 6 Kapsul",
  "Garnier Color Naturals 1 (Hitam Alami) 60 ml",
  "Hepachol 10 Kapsul",
  "Tykonib 400 mg 30 Tablet",
  "SGM LLM+ 200 g",
  "Novastan Suspensi 60 ml",
  "OB Herbal Junior Sirup 60 ml",
  "Royal Canin Adult Dog Chihuahua 85 g",
  "Nutrimax C Max 1000 2 Botol (30 Tablet/Botol) - Hemat Borongan",
  "Kondom Fiesta Ultra Safe Isi 3",
  "MegRhythm Steam Eye Mask Lavender 5 Lembar",
  "Blackmores Multivitamins + Minerals 2 Botol (30 Tablet/Botol) - Hemat Borongan",
  "Dee Dee Children Body Wash Apple 225 ml",
  "Cap Dragon Minyak Kayu Putih 60 ml",
  "Leivy Shower Cream Royal Jelly & Honey 250 ml",
  "Selsun Blue 5 Shampo 200 ml",
  "VCO Palem Mustika 100 ml",
  "Safi White Natural Anti Acne Cleanser Tea Tree Oil 100 g",
  "Emina Lipstick Creamatte 01 Chocolava",
  "Vitakraft Poesie Deli Sauce With Tender Chicken Fillet 85 g",
  "Senka Perfect Whip Fresh 50Gr",
  "Gratheos 50 mg 10 Tablet",
  "Hills Prescription Diet I/D Digestive Care for Small Breed Dog 1.5 kg",
  "Hot In Cream Strong Botol 120 ml",
  "Hada Labo Gokujyun Premium Ultimate Moisturizing Lotion 100 ml",
  "Sanmol Forte Sirup 60 ml",
  "Solinfec Cream 5 g",
  "Sohobion 200 mg 10 Tablet",
  "Tolak Angin Cair Plus Madu 15 ml 12 Sachet",
  "Kojima 100 ml",
  "Hemaviton Jreng Plain Granul 4 g 6 Sachet",
  "DoCare Wash Gloves 18 Sheet Parfume",
  "Dulcolax Pediatric 5 mg 6 Suppositoria",
  "Pet8 Dog Biscuits Mix Flavour (Bone) 110 g",
  "Eperisone 50 mg 3 Strip (10 Tablet/Strip) - Hemat Borongan",
  "Norflam 10 Kapsul",
  "Natures Protection Adult Dogs All Breeds Extra Salmon 2 kg",
  "Cattyman Creamy Milk Puree (Liquid Snack) for Cat 90 g",
  "Pigeon Baby Laundry Detergent Refill 450 ml",
  "Hunny Bunny Blue 2 Color Softlens Minus",
  "Lusty Bunny Nasal Aspirator",
  "Biosepty Odor Extinguisher 100 ml",
  "Light Meal Granola Bar Original 11 Pieces",
  "Gastridin 150 mg 10 Tablet",
  "Vicee 500 Rasa Strawberry 2 Tablet",
  "Muscle First Pro Whey 100 2Lbs Whey Protein Vanila Kurma Madu 900 g",
  "We Care Adult Diapers L 2 Pieces",
  "Nekko Tuna Topping Shrimp And Scallop Cat Wet Food Pouch 70 g",
  "My Baby Kids Body Wash Cool & Fresh 180 ml",
  "Sleek Hand Wash Reffil Lemon 400 ml",
  "Oppo Sacro Lumbar Support 2068 Size L",
  "Freshkon Maschera Jade 2 Color Softlens Minus",
  "Tensocrepe 10 cm X 4.5 m",
  "Triatec 5 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Love Eat Dog Food Chicken & Salmon 90 g",
  "Movix 15 mg 10 Tablet",
  "My Baby Minyak Telon Plus Lavender 150 ml",
  "Starmag Double Impact 4 Tablet",
  "Optimum Nutrition Amino Energy Orange Cooler 270 g",
  "Cap Kaki Tiga Balsam Hijau 20 g",
  "Curcuma Plus Gold Jeruk 100 ml",
  "Serenity Walking Stick FS-921",
  "Palmolive Shower Gel Absolute Relax Pump 750 ml",
  "Stimuno Sirup Rasa Original 100 ml",
  "OMZ 20 mg 5 Strip (6 Kapsul/Strip) - Hemat Borongan",
  "Lasegar Strawberry 320 ml",
  "Freshcare Roll On Minyak Angin Green Tea 10 ml",
  "Transpulmin Kids Balsam 10 g",
  "Nifedipine 10 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Protop 20 mg 14 Kapsul",
  "Sensitif Vivo Passionate Dots 3 Pieces",
  "Canderin 16 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Loreal Lipstick Shine On By Color Riche 911 Mauve Intensite",
  "Nutrisalin Garam Diet 200 g",
  "Glumin XR 750 mg 15 Kaplet",
  "Fasolon Cream 5 g",
  "Senka Perfect Whip Collagen In 120 g",
  "Vidoran Smart Rasa Strawberry 25 Tablet",
  "Recustein 300 mg 10 Kapsul",
  "Vitakraft Adult Cat Stick Mini Turkey & Lamb 3 Sticks",
  "Pureco Liquid Detergent Lavender 500 ml",
  "Suu Balm Gentle Moisturizing Facial Cleanser 100 ml",
  "Rohto Cool Eye Drop 7 ml",
  "Whiskas Adult Cat 1+ Years Tuna & White Fish Flavor 6 pouch (@ 80 g)",
  "Nucral 500 mg 10 Tablet",
  "Johnsons Baby Hair & Body Bath Top To Toe 200 ml",
  "La Tulipe Two Function Cake P10",
  "Sumo Cat Premium Cat Litter Cappucino 10 L",
  "Royal Canin Puppy Golden Retriever 12 kg",
  "Mamy Poko Pants X-Tra Kering XXL 6 Pieces",
  "Nutriwell Vitamin D3 1000 IU 90 Kapsul",
  "Manuka Health mgo 115+ 250 g",
  "Xanturic 300 mg 10 Kaplet",
  "Goon Pants M 32 Pieces",
  "Safi Age Defy Gold Water Essence 30+30 ml",
  "Peptibren Kacang Hijau 195 g",
  "Wardah Soft Scrub Olive 150ml",
  "Konigen Eye Drop 0.3% 5 ml",
  "Viva White Clean & Mask Refreshner for Dry Fine Wrinkle Skin 50 g",
  "Fancy Feast Inspirations With Salmon",
  "Kid-D Sirup 60 ml 2 Botol - Hemat Borongan",
  "Dodo Water Filled Teether",
  "Gatsby Water Gloss Hard 150 g",
  "Azvit 30 Tablet",
  "Wardah Instaperfect Lipstick Mattetitude Matte Stain 03 Femme 3.5 g",
  "Bicorsan Sirup 60 ml",
  "Newspar Tablet 200 mg",
  "Aatas Adult Cat Seafood Delight Tuna & Sardine Flavour 1.2 kg",
  "Farleys Biskuit Bayi Original 120 g",
  "Proris Forte Suspensi 50 ml",
  "Natur Hair Tonik Ekstrak Aloe Vera 125ml",
  "Vegeta Scrubber 6 Sachet",
  "Laflanac 25 mg 10 Tablet",
  "Dodo Nail Clipper",
  "Imunped Drops 15 ml",
  "Lifree Popok Dewasa Perekat M 9 Pieces",
  "Super Cat Adult Tuna & Chicken 85 g",
  "Herbana Balance Madia Cool Down 10 Kaplet",
  "Promedex Sirup 60 ml",
  "Watsons Animal Design Mask Brown Rice",
  "Garnier Sakura Glow Hyaluron Booster Serum 30 ml",
  "Pulmosol Rasa Creamy Vanilla 150 g",
  "Goku Disinfektan Spray 280 ml",
  "Popoku Pants XL 32 Pieces",
  "Woods Peppermint Expectorant Sirup 100 ml",
  "Hartz Dog Shampoo Extra Gentle Soothing Oatmeal with Chamomile Essential Oil 532 ml (18 Oz)",
  "Berlosid 10 Tablet",
  "Mustela Barrier Cream 50 ml",
  "Hakubi Q10 Cream 35 g",
  "Wardah Lipstick Exclusive 34 Sweet Orchid 3.8 g",
  "Carmed Lotion 50 ml",
  "Asthin Force 4 mg 2 Strip (10 Kapsul/Strip) - Hemat Borongan",
  "Childlife Vitamin C 4 Oz (118.5 ml)",
  "Sure Grow Chewable Tablets For Growing Puppies 100 Tablet",
  "Laurier Active Day Super Maxi Wing 10 Pads",
  "Milna 6-12 Biskuit Bayi Original 130 g",
  "MIPI (Minyak Pijit) 30 ml",
  "Appeton 60 Plus Rasa Vanilla 400 g",
  "Fiesta Strawberry Lubricant Gel 50 ml 2 Botol - Hemat Borongan",
  "Nivea Facial Foam Sparkling White 100G",
  "Ritez Drops 10 ml",
  "Actos 30 mg 2 Box (14 Tablet/Box) - Obat Rutin",
  "Sominal 25 mg 10 Tablet",
  "Guardian Kids Care Strawberry Yoghurt Head To Toe Wash 750 ml",
  "Royal Canin Adult Regular Sensible 33 Dry 400 g",
  "Tequinol 500 mg 10 Kaplet",
  "Venaron Hd 10 Kaplet",
  "Hydro Coco Vita-D 330 ml",
  "Futalin 10 Tablet",
  "Grotein 10 Kapsul",
  "Accu Chek Active 50 Test Strips",
  "Imodium 2 mg 10 Tablet",
  "Losartan 50 mg 10 Tablet",
  "Evangeline Eau De Parfum Natural Spray Evolve 100 ml",
  "Royal Canin Adult Indoor Long Hair Dry 400 g",
  "Cendo Posop Minidose 0.6 ml",
  "Tensivask 5 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Elopro Gel 10 g",
  "Trozinc Syrup 60 ml",
  "Royal Canin Adult Aroma Exigent Dry 2 kg",
  "Ataroc Sirup 60 ml",
  "Nordic Naturals Epa Extra Lemon 60 SoftGel",
  "Vitabiotics Ultra Vitamin B Complex 60 Tablet",
  "Drypers Pants L 28",
  "Nourish Beauty Care Acne Gel 10 ml",
  "Statcol 10 mg 10 Tablet",
  "Interpril 10 mg 10 Tablet",
  "Sandimmun Neoral Kapsul 50 mg",
  "Corovit 10 Kaplet",
  "Vitamin B Complex 2 Strip (10 Tablet/Strip) - Hemat Borongan",
  "Nospirinal 80 mg 10 Tablet",
  "Pedigree Chicken & Vegetables Flavour Adult Dog Dry Food 3 kg",
  "Tracne 0.1% Cream 20 g",
  "Ponds BB Magic Powder 50 g",
  "UO 10% Krim 20 g",
  "Wardah Colorfit Velvet Matte Mousse Lip 12 Chic Terracotta",
  "Diabetamil Sweetener 50 Sachet",
  "Revlon Colorsilk Medium Golden Brown 043",
  "Vipalbumin 2 Box (30 Kapsul/Box) - Hemat Borongan",
  "Living Color Lovely 2 Tone Blue 2 Color Softlens Minus",
  "Rudy Hair Tonic Gingseng 225 ml",
  "Ramipril 2.5 mg 10 Kaplet",
  "Royal Canin Mature Senior Consult For Medium Dogs Over 7 Years 3.5 kg",
  "OBH Nellco Special PE Sirup 55 ml",
  "Halykoo Soothing Throat spray with hyaluronic Acid 15 ml",
  "Dodo Nipple Deluxe S",
  "Buds Organics Toothpaste With Fluoride Strawberry 3-12 Tahun 50 ml",
  "Tor Men Disposable Viscose Xl",
  "Panadol Extra 3 Strip (10 Kaplet/Strip) - Hemat Borongan",
  "Pawlosophy Puppy Shampoo 500 ml",
  "Ulvid 1000 IU 10 Tablet Kunyah",
  "Tropiclean Luxury 2 in 1 Papaya & Coconut Pet Shampoo And Conditioner 355 ml (12 Oz)",
  "Mucos 30 mg 10 Tablet",
  "Himalaya Shallaki 60 Kapsul",
  "Blood Corn 50 cm Size S-M 4 Panty Pads",
  "Diquas 5 ml",
  "Ferlin Drops 30 ml",
  "Acuvue Moist 1 Day 30 Clear Softlens Minus",
  "Sequest Powder",
  "Safe Care Roll On Aromatherapy 30 ml",
  "Ketricin Orabase 0.1% Salep 5 g",
  "Scanaflam Tablet 25 mg",
  "Kondom Artika Gerigi Isi 3",
  "Ryzicor 10 mg 10 Tablet",
  "Faxiden 20 mg 10 Kaplet",
  "Farsiretic 40 mg 10 Tablet",
  "Bigen Powder Hair Dye Brown Black",
  "Nice Tuna Cat Dry Food 500 g",
  "Cussons Baby Milk Bath Soft & Smooth 100 ml",
  "B&B Kids Barbie Facial Foam Squalene 60 g",
  "Happy Dog Vet Adult Intestinal 1 kg",
  "Vomarin Flash 10 mg 10 Tablet",
  "MIPI Cream 15 g",
  "Wardah Seaweed Balancing Facial Wash 60 ml",
  "Jf Sulfur Acne Care Foam 70 g",
  "Natur-E Active Beauty Face Mist 95 ml",
  "Herbacure Naturprost 40 Kapsul",
  "Blephasep Eyelid Hygiene Gel 40 g",
  "Lactogrow 3 Plain 750 g",
  "Oxopi Sirup 60 ml",
  "Divask 5 mg 10 Tablet",
  "Fitbon 6 Kaplet",
  "Ixor 150 mg 10 Tablet",
  "Pocari Sweat 900 ml",
  "Leivy Shower Cream Goats Milk Refill 900 ml",
  "Hartz Cat Shampoo Hairball Control 444 ml (15 Oz)",
  "Cessa Baby Fedrop (Fever Drop) Essential Oil 8 ml 2 Botol - Hemat Borongan",
  "Eskulin Spray Cologne Japan Spring Melody 110 ml",
  "Cap Lang Minyak Angin 3 ml",
  "Wardah White Secret Pure Bright Clean 150ml",
  "Sidola Minyak Kayu Putih 15 ml",
  "Interco 500 mcg 10 Kapsul",
  "Mustika Ratu Pembersih Sari Sekar Gambir 150 ml",
  "Good Life Vit D 1000 100 Tablet",
  "Kenny Hair Spray Black Colour 50 ml",
  "Buscopan 10 mg 10 Tablet",
  "Xepamol 500 mg 10 Tablet",
  "Dee Dee Childrens Hair Shampoo Grape 45 ml",
  "Heinz Chocolate Biscotti",
  "Nistrol 10 mg 10 Tablet",
  "Rohto Eyeflush 150 ml",
  "Schick Shave Guard Sensitive Lime Foam 210 g",
  "Whiskas Adult Cat 1+ Years Tastymix Chicken Tuna Carrot Flavor 24 Pouch (@ 70 g)",
  "Plantacid Forte 3 Strip (10 Tablet/Strip) - Hemat Borongan",
  "Sprinkle Rasa Plain 5 Sachet",
  "Trolit granul 4 G",
  "RS Extra Virgin Olive Oil 40 ml",
  "Rechol 10 mg 10 Tablet",
  "Novorapid 3 ml 2 Flexpen - Obat Rutin",
  "Prestrenol 5 mg 10 Tablet",
  "Emina Face Toner Double The Moist 50 ml",
  "Abiranat 250 mg 120 Tablet",
  "Happy Cat Adult Turkey & Pollack 85 g",
  "ZolaGel Diaper Salep 10 g",
  "Safi Age Defy Deep Exfoliator 75 g",
  "Glucosamine 250 mg 10 Tablet",
  "Puspakids Curcuma Sirup 60 ml",
  "Hufanoxil Dry Syrup 60 ml",
  "Dove Go Fresh Revive Body Wash 550 ml",
  "Profim Dry Sirup 30 ml",
  "Halykoo Vapo Breezy Stick with Eucalyptus Oil 50 ml",
  "Ventolin Nebules 2.5 mg 5 Ampul",
  "Biodin Natural Antiseptic Gel 12 ml",
  "Femara 2.5 mg 10 Tablet",
  "Healthy Pet Healthy Cat All Stage For Kitten & Adult 7.5 kg",
  "Meixam 500 mg 10 Kapsul",
  "Baby Huki Botol Orthodontic Round PP With Handle 240 ml",
  "Cici Cat Wet Food Ocean Fish 400 g",
  "Hemaviton Action 30 Kapsul",
  "Refaquin Cream 15 g",
  "Dilatamol 100 mcg Canister",
  "Sum Cream (Sumbawa Cream Oil) 120 ml",
  "Vitamin B1 50 mg 10 Tablet",
  "Madu Mahabbah 350 g",
  "Epexol 30 mg 10 Tablet",
  "Avoskin Your Skin Bae Vitamin C 3% + Niacinamide 2% + Mandarin Orange Fruit Extract Serum 30 ml",
  "Princess Excellence Chicken",
  "Vitamin K4 Diacetate 10 mg 100 Tablet",
  "Betamin 100 mg 100 Tablet",
  "Estamin - C 100 Rasa Lemon 7 Sachet",
  "Beaphar Duo-Active Skin & Coat Multivitamin Paste For Dog 100 g",
  "JF Sulfur Acne Protect Facial Foam 70 g",
  "Family Dr Knee Support Basic M",
  "Panty-O Ladies Size M",
  "Wardah Anti Aging Night Cream 30G",
  "Endovelle 2 mg 28 Tablet",
  "Minyak Aromaterapi Tolak Angin Care Roll On 10 ml",
  "Fasfit C 10 Kapsul",
  "Serenity Steel Wheel Chair SR-862 (Random Warna)",
  "Hemaviton Jreng T8 Madu 4 g 10 Sachet",
  "Ceradan Ceramide-Dominant Skin Barrier Cream 30 g",
  "Colcitine 0.5 mg 10 Tablet",
  "Coaprovel 150 mg/12.5 mg 2 Strip (14 Tablet/Strip) - Obat Rutin",
  "Herbesser CD 200 mg 3 Strip (10 Kapsul/Strip) - Obat Rutin",
  "Tokyo Night Pomade Lavender Green 50 g",
  "MSKIDS Baby Mild Shampoo 250 ml",
  "Biolane Gentle Cleansing Milk 200 ml",
  "Mamas Choice Stretch Mark Cream 100 ml",
  "Loria Acne Lotion 30ml",
  "Paseo Cleansing Wipes Antibacterial 50 Sheets",
  "Good Life Proliver Kaplet",
  "Wellness Mega B Complex 30 Tablet",
  "Sea-Quill Joint Mover 60 Tablet",
  "Nivea Deodorant Whitening Happy Shave Roll On 50 ml",
  "Sammoxin Forte 500 mg 10 Kaplet",
  "Nipe Expectorant Adult 60 ml",
  "Trileptal Tablet 300 mg",
  "Snappy Tom Chicken 400 g",
  "Eskulin Kids Shower Gel Sofia 250 ml",
  "Oxypen 6 Kaplet",
  "Happy Dog Vet Adult Hypersensitivity 12 kg",
  "Lifebuoy Mild Care Bar 85 g",
  "Head & Shoulders Clean & Balanced Shampoo 180ml",
  "Tresnojoyo Joybee Madukids Strawberry 60 ml",
  "Dee Dee Childrens Shampoo for Long Hair Rose 200 ml",
  "Santa-E 100 IU 30 Soft Capsules",
  "Tizanidine 2 mg 10 Tablet",
  "Cap Lang Minyak Telon 60 ml",
  "Betaloc Zok 25 mg 14 Tablet",
  "Fibramed 300 mg 6 Kapsul",
  "Proplan Adult Dog Essential Health Large Chicken Formula Dry 15 kg",
  "Cap Kaki Tiga Balsam Kuning 20 g",
  "Examination Gloves Size S 200 Pieces",
  "Mu Touch Shower Scrub Goats Milk Argan Oil And Walnut 940 ml",
  "Minyak Telon Jmk 60 ml",
  "Durex K-Y Jelly Personal Lubricant 50 g",
  "Kenalog in Orabase 0.1% Salep 5 g",
  "Frontline Spray for Dogs & Cats 100 ml Solutions",
  "Veet Hair Removal Kulit Normal Cream 25 g",
  "OB Herbal 60 ml",
  "Celebon Collagen Essence Mask Vitamin 23 g",
  "My Baby Kids Body Wash Soft & Smooth 180 ml",
  "Tjing Tjau Balsam 36 g",
  "Vitalis Body Scent Glamour Fantasy 120 ml",
  "Boemeal 60 Kapsul",
  "Imdur 60 mg 15 Tablet",
  "Physiomer Baby Nasal 115 ml",
  "Inflason 5 mg 10 Tablet",
  "Sensi Convex Mask 4 Ply Earloop Blue 20 Pieces",
  "Sebamed Cleansing Bar 100 g",
  "Biore Body Foam Hygienic Cool 250 ml",
  "Kondom Durex Love 2 Box (12 Pieces/Box) - Hemat Borongan",
  "Vicalcin Sirup 60 ml",
  "Ciao Chu-Ru Grilled Chicken Fillet Crab Flavor 20 g",
  "Polycrol Forte Sirup 180 ml",
  "Choicemmed Fingertip Pulse Oximeter MD300CN310",
  "Hecosan Herbal Cough Syrup 60 ml",
  "Dumocalcin 500 mg Peppermint 10 Tablet",
  "Ostelox 7.5 mg 10 Tablet",
  "Onetic 8 mg 10 Tablet",
  "Baby Dee Talcum Powder Milk 100 ml",
  "Vitamin C 250 mg 10 Tablet",
  "Pantozol 40 mg 7 Tablet",
  "Rosufer 10 mg 10 Tablet",
  "Cussons Baby Wipes Fresh & Nourish 50 Lembar",
  "Angintriz MR 10 Tablet",
  "Bebelove 1 Formula Bayi Bubuk 800 g",
  "Babymoov Milk Dispenser A04212",
  "Teh Celup Jati Cina 25 Sachet",
  "Shantos Romeo Hair Styling Pomade Type Gold 75 g",
  "Instance Gel Hand Sanitizer 100 ml",
  "Sweety Gold Comfort Nb 52 Pieces",
  "Madu AM Royal Jelly Super Plus Bee Polen 250 ml",
  "Elkana Suspensi 60 ml",
  "Levopront Sirup 120 ml",
  "Vienna Blue Horse Nourish & Repair Hair Serum 65 ml",
  "Pixy Lip Cream 03 Classic Red 4 G",
  "Bigen Speedy 882 Brownish Black",
  "Fishermans Friend Rasa Mandarin and Ginger Sugar Free",
  "Masflu Forte 10 Tablet",
  "Bioplacenton Gel 15 g 2 Tube - Hemat Borongan",
  "Channa 500 mg 10 Kapsul",
  "Mam Bottle Anti Colic 260 ml 1 Pieces (Random Warna)",
  "Masker Evo Plusmed Earloop Orange 25 Pieces",
  "Hi-D 1000 Vitamin D3 5 Strip (6 Tablet Kunyah/Strip) - Hemat Borongan",
  "Mextril 4 Tablet",
  "Advocate for Large Cat 4 kg - 8 kg 0.8 ml Tube",
  "Strocain P 400 mg 10 Tablet",
  "Antis Hand Sanitizer Jeruk Nipis Spray 200 ml",
  "Wellness Odorless Garlic 500 mg 60 Kapsul",
  "Vaseline Repairing Petroleum Jelly 50 ml",
  "Whisper Heavy Flow Overnight Wings 8 Pads",
  "Refocare Thickness 0.37 Mm Ukuran 5X5 Cm 5 Pieces",
  "Neutrogena Deep Clean Brightening Foaming Cleanser 40 g",
  "Banana Boat Aloe Vera Gel 230 g",
  "Madu Vitomata 280 g",
  "Janumet 50 mg/500 mg 4 Strip (7 Tablet/Strip) - Obat Rutin",
  "Blink N Clean Lens Drops 15 ml",
  "Boost D 5000 IU 10 Tablet",
  "Wellness Excell C 500 mg 60 Tablet",
  "Octadin Cairan Antiseptik Spray 50 ml",
  "Natesh Day 10 Pads",
  "Dodo Soother S 050",
  "Madu TJ Masuk Angin 140 g",
  "Dettol Wipes Original 50 Lembar",
  "Royal Canin Adult Cat Hepatic Dry 2 kg",
  "Happy Dog Naturcroq Puppies Welpen 4 kg",
  "DHC Folic Acid + Vit B 7 Tablet",
  "Melomet 0.1% Krim 10 g",
  "Ponds Age Miracle Whip Day Cream 50 g",
  "X2 Yearly 3 Clear Softlens Minus",
  "Wardah Colorfit Velvet Powder Foundation 42N Neutral Sand",
  "Accu Chek Instant 25 Test Strips",
  "Salicyl Talk Ika 80 g",
  "Gracivask 5 mg 10 Tablet",
  "Popoku Pants XXL 14 Pieces",
  "M-Pets Puppy Shampoo 250 ml",
  "Nexcare Masker Daily Earloop 3+1 Pieces",
  "Larutan Penyegar Cap Badak Rasa Anggur 320 ml",
  "Hand Sanitizer 240 ml",
  "Pet Choice Cat Food Salmon Chicken 340 g",
  "Whiskas Adult Cat 1+ Years Chicken Flavor 1.2 kg",
  "Mokbios 500 mg 10 Kaplet",
  "Diabetasol Zero Calorie Sweetener 50 Sachet",
  "Golden West Cat Litter Fragrance Lemon 10 L",
  "Scabicid Cream 10 g",
  "OBH Tropica Extra Anak Rasa Jeruk Sirup 60 ml",
  "Genalsik 80 mg 10 Tablet",
  "Manuka Health mgo 115+ 500 g",
  "Bio Essence Bio-Renew Nourishing Toner 100 ml",
  "Whiskas Senior Cat 7+ Years Mackerel Flavor 24 Pouch (@ 85 g)",
  "Olay Total Effect 7 in One Day Cream Normal SPF15 12 g",
  "Cetop Zink 60 Tablet",
  "Mirael Sugar Waxing Kit Refreshing Apple 210 ml",
  "Vectrine 300 mg 10 Kapsul",
  "Holikalk 10 Tablet",
  "Arfen 400 mg 10 Kaplet",
  "Floxifar 500 mg 10 Kaplet",
  "Divoltar 50 mg 10 Tablet",
  "Calorloss 1000 mg 6 Tablet",
  "Hemaviton C1000 Total Care Orange Serbuk 5 Sachet",
  "Calpico Anggur Blueberry 70 ml",
  "Ronazol Sirup 60 ml",
  "Lauramox Forte 500mg 10 Kaplet",
  "Natures Boss Kunyit Putih 30 Kapsul",
  "Apolar N Cream 10 g",
  "Blopress 8 mg 4 Strip (7 Tablet/Strip) - Obat Rutin",
  "Onemed Masker Earloop Jilbab 50 Pieces",
  "Cleo Kitten Food Ocean Fish Flavor 1.2 kg",
  "B&B Hair & Body Wash Rainbow Dash Botol 280 ml",
  "Vioquin 500 mg 10 Kaplet",
  "Scopma 10 mg 10 Kaplet",
  "A-B Vask 10 mg 10 Tablet",
  "Ibuprofen 400 mg 10 Tablet",
  "Adrome 10 mg 10 Tablet",
  "Gillette Foamy Lemon Lime 50 g",
  "Prive Uricran Plus 8 gr 5 Sachet",
  "Miratadin Sirup 60 ml",
  "Cap Lang Balsam Aktiv 20 g",
  "Tresnojoyo Joybee Madukids Original 100 ml",
  "Actos 30 mg 14 Tablet",
  "Kambium Kapas Bola 100 Pieces",
  "Hakubi White C 90 Tablet",
  "Pet8 Sasami Stick Liver French Flavour 75 G",
  "Me-O Creamy Treats Salmon Flavor 4 Sachet",
  "Momami Softie Top To Toe Wash 235 ml",
  "1St Choice Adult Dog All Breeds Dental Health 12 kg",
  "Prama Dog Snack Chicken Liver 70 g",
  "Airborne Chewable Citrus 32 Tablet",
  "Mega We Care Ferrovit Plus 10 Kapsul",
  "Sariayu Intensive Acne Care 12 ml",
  "Temptations Snack Kucing rasa Tempting Tuna 30 g",
  "Cendo Genta 0.3% Minidose 0.6 ml",
  "Mucos Sirup 60 ml",
  "Loreal Excellence 3 Natural Dark Brown Creme",
  "Kondom Fiesta Black Coffee Isi 3",
  "Solpenox Dry Sirup 60 ml",
  "Selsun Gold Shampo 60 ml",
  "Glow Premium Pet Shampoo Silky And Soft 300 ml",
  "Daktarin Cream 10 g 2 Tube - Hemat Borongan",
  "Advocate for Large Dogs 10 kg - 25 kg Tube 2.5 ml",
  "Clinelle Age Revive Lifting Emulsion 80 ml",
  "Synalten Cream 5 gr",
  "Renator 500 mg 10 Tablet",
  "Nivea Micellar Water Hydration 200 ml",
  "CeraVe Moisturising Lotion 88 ml",
  "Omegdiar Suspensi 60 ml",
  "Panty-O Ladies Size XXL",
  "Pet Derm for Cat Tablet",
  "Cendo LFX Minidose 0.6 ml",
  "Enervon-C Plus Sirup 120 ml",
  "Kitchen Flavor Grainfree Baby Cat & Kitten Food 1.5 kg",
  "Nifedin 10 mg 10 Tablet",
  "Yarizine 10 mg 10 Tablet",
  "Eyelovin Mite Clair Wendy Brown Softlens Minus",
  "Costan Forte 500 mg 10 Kaplet",
  "SGM Eksplor 3 Plus Complinutri Madu Susu Bubuk 400 g",
  "Cap Lang Minyak Urut Gpu Sereh 100 ml",
  "Pyrazinamide 500 mg 10 Tablet",
  "Senka Perfect Whip White 50 g",
  "Toro Toro Tuna Plus Fiber 5 Sachet",
  "Gatsby Pomade 30G",
  "Nolipo 500 mg 10 Kapsul",
  "Panadol Extra 10 Kaplet",
  "Pixy Two Way Cake Perfect Fit 01 White Cream 12.2 g",
  "Amlocor 5 mg 10 Tablet",
  "Serenity Steel Wheel Chair Jari-Jari SR-809PC",
  "Levazide 6 Tablet",
  "Medicrepe 4 Inchi (10 cm X 4.5 M)",
  "La Tulipe Two Function Cake Y15",
  "Ul Arabia 60 Tablet",
  "Hills Prescription Diet H/D Heart Care Chicken Flavour Food for Dog 1.5 kg",
  "Happy Dog Naturcroq Adult Beef & Rice 4 kg",
  "Vitacid 0.05% Gel 20 g",
  "Nivea Intensive Moisture Body Lotion 200 ml",
  "Pixy Lip Cream 04 Fun Fuschia 4 G",
  "XL Professional Peach & Kiwi Hair Mask 25 g",
  "Omepros Mini Caps 10 Kapsul",
  "Glimepiride 2 mg 10 Strip (10 Tablet/Strip) - Obat Rutin",
  "Cosrx Centella Water Alcohol Free Toner 150 ml",
  "Maybelline Lipstick Color Sensational The Powder Mattes Avenue C",
  "Nutrimax Vitamin D3 1000 IU 2 Botol (60 Tablet/Botol) - Hemat Borongan",
  "Pure Kids Fever Free Sachet",
  "Kondom Fiesta Delay Isi 3",
  "Biolane Skin Freshening Fragrance 200 ml",
  "Happy Dog Supreme Mini Adult 1 kg",
  "Alcet Sirup 60 ml",
  "Amaryl M 1 mg/250 mg 10 Tablet",
  "SGM Eksplor Advance+ Soya/ Isopro Soy 1 Plus Vanila Formula Susu Bubuk 700 g",
  "Nestle Acticor Chocolate 85 ml",
  "Broncho-Vaxom Children 3.5 mg 10 Kapsul",
  "Diprosone-OV 0.05% Cream 10 g",
  "Kaltrofen 100 mg 10 Tablet",
  "Sensitif Vivo 0.03 12 Pieces",
  "Sikstop 90 mg 10 Tablet",
  "Kahf Face Wash Oil And Acne Care 100 ml",
  "Nr Shampoo Arnika 200ml",
  "Alpo Adult Chicken Liver And Vegetable 10 kg",
  "My Baby Soap Fresh Fruity 100 g",
  "Ocufresh Tetes Mata 5 ml",
  "Obhdryl Sirup 100 ml",
  "Natural Wellbetx Comdiab Multivitamin & Mineral Formula 60 Tablet",
  "Borobudur Darsi 60 Kapsul",
  "Leukoplast (1622) 2.5 cm x 4.5 m",
  "Elovess 10 Kapsul",
  "Cendo Tropine 0.5% Minidose 0.6 ml",
  "Natur-E Active Beauty Natural Vitamin E 300 IU 2 Box (32 Kapsul/Box) - Hemat Borongan",
  "Akurat Test Kehamilan Compact 2 Pieces - Hemat Borongan",
  "Domedon Sirup 60 ml",
  "Paramorina OBP Sirup 100 ml",
  "Sebamed Childrens Shampoo 150 ml",
  "Royal Canin Adult Dog Gastrointestinal High Fibre 2 kg",
  "Klinsen Shower Scrub Mineral Spa 1000 ml",
  "Lodoz 2.5 mg 10 Tablet",
  "Amlodipine 5 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Ciao Cat Liquid Snack Chicken Fillet & Squid 4 Sachet",
  "Soyjoy Banana 30 g",
  "Love Eat Dog Food Tuna 90 g",
  "Pure Baby Hand & Mouth Wipes Aloe Vera 60 Pieces",
  "Wardah Exclusive Matte Lip Cream 11 Oh So Nude",
  "Moteson Cream 10 g",
  "Pronicy 4 mg 10 Kaplet",
  "Happy Cat Vet Adult Intestinal Wet Food 100 g",
  "Oilum Body Wash Brightening Scrub 210ml",
  "Madurasa Jeruk Nipis 12 Sachet",
  "Trolip 160 mg 10 Tablet",
  "Norvask 10 mg 10 Tablet",
  "Milna 6+ Bubur Organic Pisang 120 g",
  "Ristra Extremely Gentle Cleansing Milk 150 ml",
  "LP Support Shin & Calf Sleeve (718) Size L",
  "Neuvis Pro 500 mg/5 ml Sirup 60 ml",
  "WRP Cookies Chocolate Chip isi 12",
  "Alkohol 70% 300 ml",
  "Bio Strath Sirup 100 ml",
  "Pratifar 40 mg 10 Kaplet",
  "Pedab 80 mg 10 Tablet",
  "Ponds Men White Boost Facial Scrub 50 g",
  "Durex Play Feel 100 ml",
  "Candepress 8 mg 10 Tablet",
  "Enervon Gold 30 Kapsul Lunak",
  "Fresh Living Essential Oil Eucalyptus Lavender 10 ml",
  "Laserin Madu Sirup 30 ml",
  "Eskulin Kids Hair & Body Wash Sofia 280ml",
  "Lux Body Wash White Impress 220ml",
  "Clabat Forte Dry Sirup 60 ml",
  "Serenity Ear Tips Hearing Aid SR-80 BTE",
  "Prenagen Mommy Moka 400 g",
  "My Baby Lotion Telon Plus 60 g",
  "Happy Cat Vet Adult Struvit 1.4 kg",
  "Soffell Bengkoang 80 g",
  "Cystaid Plus Kapsul",
  "Cap Lang Gpu Cream Minyak Sereh 150 g",
  "Rheu-Trex 10 Tablet",
  "Neosma 2.5 mg 10 Kaplet",
  "Alkohol 70% 500 ml",
  "Borobudur Bilon 100 Kapsul",
  "Betadine Skin Cleanser Antiseptic 100 ml",
  "Cussons Baby Milk Bath Fresh & Nourish 200 ml",
  "Pionix 15 mg 10 Tablet",
  "Labore Sensitive Skin Care Gentlebiome Skin Nutrition Gel 50 ml",
  "Channa Plus 3 Sachet",
  "Pedigree",
  "Mamy Poko Pants X-Tra Kering L 30 Pieces",
  "Piroxicam 10 mg 3 Strip (10 Tablet/Strip) - Hemat Borongan",
  "Nexium Mups 20 mg 10 Tablet",
  "Labore Sensitive Skin Care Gentlebiome Thermal Soothing Mist 100 ml",
  "Bestmed Masker Earloop 3 Ply 50 Pieces",
  "Omeric 300 mg 10 Tablet",
  "Propranolol 10 mg 10 Tablet",
  "Treelains C 1000 Time Release 30 Tablet",
  "Farnormin 50 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Cefacef 200 mg 10 Kaplet",
  "Rexavin 500 mg 10 Kaplet",
  "Cussons Baby Hair Lotion Avocado & Pro Vit B5 100 ml",
  "Alegi 10 Tablet",
  "Zacoldine Sirup 60ml",
  "Cap Ayam Minyak Kayu Putih 150 ml",
  "Gasol Ubi 200 g",
  "H2 Health & Happiness Pureway C+ 30 Tablet",
  "Hills Science Diet Healthy Cuisine Adult 1-6 Chicken",
  "Adem Sari Ching Ku Herbal Lemon Botol 350 ml",
  "Nairet 2.5 mg 10 Tablet",
  "Nu Health L-Cal Grow 60 ml",
  "X2 Chic Blue 2 Color Softlens Minus",
  "Teenmax 350 ml",
  "Crestor 40 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Novadex 0.75 mg 10 Kaplet",
  "Ambroxol Sirup 15 mg/5 ml 60 ml",
  "Melanox Premium Whitening Cream 14 Gr",
  "Maybelline Lipstick Color Sensational The Powder Mattes Touch Of Nude",
  "Happy Dog Supreme Young Junior Original 10 kg",
  "Hi-D 1000 Vitamin D3 6 Tablet Kunyah",
  "Kojie San Kojic Acid Bar Soap 65 g",
  "Royal Canin Adult Dog Yorkshire Terrier 85 g",
  "Blackmores Daily Immune C 500 30 Tablet",
  "Strepsil Vitamin C 8 Tablet",
  "Sytin Drop 12 ml",
  "Hai Feng",
  "Best In Show Maxi Cat Sand Lavender 30 L",
  "Brainact 1000 mg 10 Kaplet",
  "Nasacort AQ Nasal Spray",
  "Top Gel Luna Natural Aqua 2 Color Softlens Plano/No Minus",
  "Euthyrox 50 mcg 2 Strip (25 Tablet/Strip) - Hemat Borongan",
  "Jamu Iboe Asi Iboe Herbal 30 Kapsul",
  "Inez Skin Clarifying Active Toner 150 ml",
  "Carpiaton 100 mg 10 Tablet",
  "Dexycol 500 mg 10 Kapsul",
  "Mesone 0.1% Salep Lemak 10 g",
  "Dr. Ortho Lumbar Support - Korset Wb 527 - XXL",
  "Enfagrow A+ 4 Vanila 800 g",
  "Nexcare Acne Cover Fun Pack",
  "Habbasyi Oil 500 mg 75 Kapsul",
  "Clarihis 10 mg 10 Tablet",
  "Fituno 30 Kaplet",
  "Afra Minyak Zaitun 500 ml",
  "Ellips Dry Shampoo Fruity 50 ml",
  "Camry Timbangan Berat Badan Digital",
  "Emina Lip Tint Magic Potion 03 Smitten",
  "Tong Kang Shuang Krim 10 g",
  "Orezinc Sirup 60 ml",
  "Moist Diane Extra Fresh & Hydrate Treatment 450 ml",
  "Beurer Blood Pressure Monitor BM26",
  "Bigroot Nose Hygiene Stuff Relief 50 ml",
  "Balance Madia Feminine Health 10 kaplet",
  "Ponds Age Miracle Double Action Serum 30 ml",
  "Fancy Feast Turkey Feast In Gravy Grilled 85 g",
  "Entrostop Herbal Sirup 15 ml",
  "Hansaplast Kasa Steril 7",
  "Mediamer B6 10 Tablet",
  "Shine Biospirulina 200 Tablet",
  "Kiranti Sehat Datang Bulan Original",
  "Serenity Commode Wheel Chair FS-609GCU",
  "Thecort 2% Cream 5 g 2 Tube - Hemat Borongan",
  "Vienna Whitening Body Scrub Goats Milk 250 g",
  "Phalsy",
  "Goo",
  "Ikamicetin 2% Salep 15 g",
  "Pureluxe Grain Free Holistic Persian Cat With Salmon 400 g",
  "Bka Botol Asi 100 ml 14 Pieces",
  "She Super Star Lyra 2 Color Softlens Minus",
  "Tresnojoyo Madu TJ Jahe Merah Mint 250 g",
  "Xylitol SF Jeruk Nipis Sachet 12 G",
  "Fastor 10 mg 10 Tablet",
  "Air Mancur Sehat Pria 4 Kapsul",
  "Nutrimax Clear Vision 60 Tablet",
  "Femmy Vitamin D3 1000 IU 10 Tablet",
  "Whiskas Junior 2-12 Bulan Ocean Fish Flavor with Milk 450 g",
  "Kobellon 20 Kapsul",
  "Cap Lang Minyak Sereh Sitronella 60 ml",
  "Me-O Creamy Treats Tuna & Scallop Flavor 4 Sachet",
  "Astina 6 mg 10 Kapsul",
  "Donepezil Hydrochloride 5 mg 10 Tablet",
  "Biolergy 50 mg 10 Tablet",
  "Jerhigh Cat Snack Chicken and Fish Bites 85 g",
  "Virbac Megaderm 8 ml Sachet",
  "Eskulin Kid Hair And Body Wash 2 In 1 Clean And Smooth 280 ml",
  "Natures Protection Adult Dogs (1-10 kg) Mini Extra Salmon 7.5 kg",
  "INAmask Surgical Face Mask Blue 50 Pieces",
  "Proplan Puppy Healthy Growth And Development Medium Chicken Formula Dry 2.5 kg",
  "Sedrofen Dry Sirup 60 ml",
  "Prenagen Emesis Vanila 360 g",
  "Jahe Merah Mantaab 10 Sachet",
  "Herbacure Naturex P 40 Kapsul",
  "Farleys Biskuit Bayi Apel 120 g",
  "Forbetes 850 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Hansaplast Salep Luka 3.5 g",
  "Pyricef 500 mg 10 Kapsul",
  "Graperide 4 mg 10 Tablet",
  "Tremenza Sirup 60 ml",
  "Osaki Maternity Napkin L 4 Pieces",
  "Dee Dee Hair Shampoo Apple 250 ml",
  "Woods Lozenges Sugar Free Lemon 6 Butir",
  "Tablet",
  "Protaz 15 mg 10 Tablet",
  "Vitakraft Dog Beef Stick With Turkey 12 g",
  "CalMas 250 Suspensi 120 ml",
  "HPJ Animal Shampoo For Dogs And Cats Flea & Tick 250 ml",
  "Futuro Comfort Lift Ankle Support Size M",
  "Cimory Plain 250 ml",
  "Derma Angel Spot Lightening Patch 12 Patch",
  "Nilapur 300 mg 10 Tablet",
  "Wardah Matte Lipstick 19 Essential Nude 3.8 G",
  "Kondom Fiesta Durian Isi 3",
  "Depakote 250 mg Tablet",
  "Letraz 2.5 mg 5 Tablet",
  "Farnormin 50 mg 10 Tablet",
  "Lanvy Syrup 100 ml",
  "Mustika Ratu Penyegar Sari Ketimun 150 ml",
  "Andalan Alat Uji Kehamilan 2 Strip - Hemat Borongan",
  "Optimax O3 10 Kapsul",
  "Yummy Bites Vegetables Flavour",
  "Zeviton Kaplet",
  "Hislorex 10 Tablet",
  "Bigroot Nose Hygiene Ultra Gentle Baby 50 ml 2 Botol - Hemat Borongan",
  "Wardah Lightening Cleansing Milk 100 ml",
  "OB Herbal 100 ml",
  "Mirasic Forte 650 mg 10 Tablet",
  "Renovit Gold 30 Kaplet",
  "Sebamed Baby Cream Extra Soft 50 ml",
  "Sido Muncul Red Ginseng 30 Kapsul",
  "Nutrilon Royal 4 Vanila Susu Pertumbuhan Bubuk 400 g",
  "Marcks Venus Water Shine Lipstick No. 4 Cheryl",
  "Seretide Inhaler Diskus 100 2 Box (1 Diskus/Box) - Obat Rutin",
  "Fitocare Minyak Telon 50 ml",
  "Pigeon Baby Liquid Soap 200 ml",
  "Pyrex Enema 125 mg/2.5 ml",
  "Fimediab 5 mg 10 Tablet",
  "Sandimmun Neoral 100 mg 50 Kapsul",
  "Dove Conditioner Total Damage Treatment 160ml",
  "Rydian 10 mg 10 Tablet",
  "Gillette Goal II 3+1 Pieces",
  "Gestiamin-Pluz 10 Kapsul",
  "Curcuma Plus Honey Vit Jeruk 100 ml",
  "Wardah Colorfit Matte Foundation 32N Neutral Beige",
  "Sukin OIl Balancing Claifying Facial Tonic 125 ml",
  "Hexcam 15 mg 10 Tablet",
  "La Roche Posay Spot Scan Acne Fighter Essentials Package",
  "Cussons Baby Liquid Cleanser 300 ml",
  "Citoviplex 10 Kaplet",
  "Nifedipine 10 mg 10 Tablet",
  "Isoptin 80 mg 10 Tablet",
  "Cotrimoxazole 480 mg 10 Tablet",
  "Herborist Body Butter Banana 80 g",
  "Baby Safe 360 Sipper Cup with Handle",
  "Gravask 10 mg 10 Tablet",
  "Avent Combined Steamer And Blender",
  "Certican 0.25 mg 60 Tablet",
  "Carmint 500 mg 30 Kapsul",
  "My Dear Cat Adult Cat Seafood 1.5 kg",
  "Kawai Gankyu Voxie Lunar Brown Softlens Plano/No Minus",
  "Johnsons Cotton Touch Top-To-Toe Hair & Body Baby Bath 200 ml",
  "Vidoran Smart Rasa Jeruk Sirup 100 ml",
  "Diproca 50 mg 28 Tablet",
  "Lipitor 20 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "Borobudur Kunti 550 mg 100 Kapsul",
  "Sauda Garlic Oil Gold 200 Kapsul",
  "Royal Canin Adult Dog Veterinary Gastrointestinal 2 kg",
  "Crown",
  "La Roche Posay Lipikar Baume AP+M 200 ml",
  "Newlook Playful Moisture Retention Blue 2 Color Softlens Minus",
  "Ottoprim 10 Tablet",
  "Revlon Ultra HD Matte Lipcolor 615 Temptation",
  "Biostatik 150 mg 10 Tablet",
  "Cendo Catarlent Eye Drops 5 ml",
  "Seed 1 Day Pure Up 32 Clear Softlens Minus",
  "Susu Curcuma Plus Rasa Vanila 750 g",
  "Pregabalin 75 mg 6 Kapsul",
  "Manuka Health mgo 263+ 250 g",
  "Softex Maternity 20 Pads",
  "Leucoplast 1624 5 cm x 4.5 m",
  "Celana Sunat Size S",
  "Nutrimax C Max 1000 30 Tablet",
  "Ameripro Cat Milk Replacer for Kitten 200 g",
  "Tresnojoyo Madu Kurma 250 g",
  "Abdelyn Drop 10 ml",
  "Cartos 10 Tablet Effervescent",
  "Paramex SK 6 Tablet",
  "Whiskas Junior 2-12 Months Mackerel Flavor 6 pouch (80 g)",
  "Dettol Body Wash Original Refill 250 ml",
  "Calciflavone 30 Tablet",
  "Thiamfilex 500 mg 10 Kapsul",
  "Gendai Biscal Dog Snack 170 g",
  "CDR Effervescent 2 Tube (15 Tablet/Tube) - Hemat Borongan",
  "Bebenice Rusks Original",
  "Farmalat ER 10 Tablet",
  "Trifamol 500 mg 100 Tablet",
  "Whiskas Adult Rasa Ocean Fish Dry 1.2 kg",
  "Bioderma Atoderm Nourishing Cream 200 ml",
  "Medichlor Suspensi 60 ml",
  "Solvita Sirup 60 ml",
  "Miozidine MR 35 mg 10 Tablet",
  "Maybelline Fit Me Dewy Smooth Foundation 220 Natural Beige",
  "Vitakraft Menu Vital for Hamster 1 kg",
  "Mirzap 30 mg 10 Tablet",
  "Yummy Bites Cereal Multigrain Pumpkin",
  "Eminox 5% 30 ml",
  "Divens Plus Sirup 100 ml",
  "Hapsen 5 mg 10 Tablet",
  "Siladex Cough Herbal Sirup 60 ml",
  "Tebokan 10 Tablet",
  "Bodrexin Pilek Dan Alergi Pe Sirup 56 ml",
  "Listerine Natural Green Tea Mouthwash 250 ml",
  "Nutrimax BRP (Brain Power) 30 Kapsul",
  "Pigeon Food Feeder 120 ml Art. 033282",
  "Sebamed Hydrating Body Lotion 200 ml",
  "Head & Shoulders Shampoo Anti Dandruff Bersih dan Harum 160 ml",
  "Ialuset Plus Cream 100 g",
  "Guardian Aloe Vera Gel 350 ml",
  "Pyrabal 500 mcg 10 Kapsul",
  "Oto Adult Pants M 8 Pieces",
  "Char Mi Cotton Bud Art 131 75 Pieces",
  "Ika Sariawan 120 ml",
  "Super Cat Adult Tuna Prime Cuts 85 g",
  "Solare Sunblock 75 g",
  "MSKIDS Daily Baby Cream 100 ml",
  "B1G1 Cessa Baby Fedrop (Fever Drop) Essential Oil 8 ml + Cessa Kids Lenire 8 ml",
  "Urixin 400 mg 10 Tablet",
  "Promina Puffs Blueberry 15 g",
  "PhysioGel Daily Moisture Care Body Lotion 100 ml",
  "Erythrin 500 mg 50 Kaplet",
  "Polysilane Sirup 100 ml 2 Botol - Hemat Borongan",
  "Divask 10 mg 10 Tablet",
  "Garnier Bright Complete Vitamin C 30x Booster Serum 15 ml",
  "Imufor Plus Sirup 60 ml",
  "Glamarol 3 mg 10 Tablet",
  "Enbatic Powder 3 G",
  "Bambi Baby Compact Powder 40 g",
  "Happy Cat Adult Sterilised Atlantic Salmon 1.4 kg",
  "Fitkom Gummy Go",
  "Lactogen 1 750 g",
  "Johnsons Baby Cologne Heaven 100 ml",
  "Kaloba 20 mg 21 Tablet",
  "Galstar 100 mg 10 Tablet",
  "Chil Kid Platinum Rasa Vanila 800 g",
  "Cap Lang Minyak Kayu Putih 15 ml",
  "Dodo Sport Handle Cup Small 100 ml",
  "Andalan Laktasi 2 Strip (28 Tablet/Strip) - Hemat Borongan",
  "Galten Kaplet",
  "Dodo Silicone Nipple L 36 Pieces",
  "Cendo Fenicol 0.5% Eye Drops 5 ml",
  "Ezol 20 mg 7 Tablet",
  "Hansaplast Roll Kain 1.25 cm x 5 m",
  "Lasal 4 mg 10 Kapsul",
  "Futuro Stabilizingbs Back L-XL",
  "Triatec 2.5 mg 10 Tablet",
  "Cussons Baby Cologne Lovely Kiss 100 ml",
  "Pet8 Dog Biscuits Milk Flavour (Round) 110 g",
  "Baby Huki Dot Super Flo M 2 Pieces",
  "Wardah Renew You Anti Aging Night Cream 17 ml",
  "Gatsby Water Gloss Super Hard 150Gr",
  "Tropiclean Dual Action Ear Cleaner 118 ml (4 Oz)",
  "Metcor 16 mg Tablet",
  "Baby Huki Bottle 240 ml",
  "Serenity Dual Head Stethoscope SR-601P Limited Edition Rainbow Dark Green",
  "Lincocin 500 mg 10 Kapsul",
  "Good Life GCM Forte 30 Sachet",
  "Hills Prescription Diet Z/D Skin/Food Sensivities Food For Dogs 13 Oz",
  "Promina Bubur Bayi Steamed Chicken Mushroom 120 g",
  "Wardah Colorfit Matte Foundation 43W Golden Sand",
  "Dodo Cotton Buds Code 122 20 Pieces",
  "Siladex Antitussive Sirup 60 ml",
  "Alkohol 90% 500 ml",
  "Ondavell ODT 4 mg 10 Tablet",
  "Frozz Permen Blueberry 15 g",
  "Linadex 15 mg 21 Kapsul",
  "Pigeon Feeding Set Cd. D301",
  "Vienna Whitening Body Scrub Strawberry 1 kg",
  "Purvit-D3 1000 IU 10 Kapsul Lunak",
  "Kondom Fiesta Max Dotted Isi 3",
  "Metphar XR 750 mg 10 Tablet",
  "Zentra 10 Kaplet",
  "Proast Sirup 60 ml",
  "Vomecho 5mg/5ml Suspensi 60ml",
  "Bioderma Sebium Gel Moussant 100 ml",
  "Nevox XR 500 mg 3 Strip (10 Tablet/Strip) - Obat Rutin",
  "LP Support Ankle Support Size M (704)",
  "Miranda for Him Styling Pomade Strong Hold & Shine 100 g",
  "Pyramid Hill Adult Dog With Lamb 400 g",
  "Vitakraft Vitalife Beauty Skin Protection 500 g",
  "Erphamazol 1% Krim 5 g",
  "Counterpain Cream 120 g",
  "Protecal C 200 mg 10 Tablet",
  "Sanorine Biru 0.025% Gargle 80 ml",
  "Mirasic Sirup 60 ml",
  "Vitalong C 30 Kapsul",
  "Glamarol 4 mg 10 Tablet",
  "Hansaplast Star Wars 7 Lembar",
  "Curcuma Plus Go Talz/Grow 20 Tablet Hisap",
  "Safe Care Roll On Aromatherapy 10 ml 3 Botol - Hemat Borongan",
  "Hycocare Kiddy Plast Boy 6 Lembar",
  "Daily C 500 mg 10 Tablet",
  "Wetties Wipes Antiseptic Extra Tebal 10 Lembar",
  "Bioion Pets Pounce Original 500 ml",
  "Pigeon Baby Powder Canned 150 g",
  "Parasol Face Sunblock Spf 33 Cream 20 g",
  "Banana Boat Sport Sunscreen SPF 50 Lotion 90 ml",
  "Calcifar Plus 10 Kaplet",
  "Ambroxol 30 mg 10 Tablet",
  "Sarang Semut 30 Kapsul",
  "Thiamycin 500 mg 10 Kapsul",
  "Happy Cat Vet Adult Hepatic 1.4 kg",
  "Optimum Creatine 2500 100 Kapsul",
  "Herbakof Stick Pack 15 ml",
  "Minyak Tawon EE 60 ml 2 Botol - Hemat Borongan",
  "Nourish Skin Ultimate 60 Tablet",
  "V Natural Brightening Soap Temulawak Extract 80 g",
  "Mesone 0.1% Cream 10 g",
  "Lapiva 5/160 mg 10 Tablet",
  "Nilatika 10 mg 10 Tablet",
  "Byemos Stiker Penolak Nyamuk 20 Lembar",
  "Bioprexum Plus 30 Tablet",
  "Betadine Skin Cleanser Antiseptic 60 ml",
  "Sea-Quill Eye-Bright 30 Tablet",
  "Vitalis Exotic Body Scent Caribbean Getaway 100 ml",
  "Benecheck Plus 3In1 Single Pack",
  "Maybelline Lipstick Superstay Matte Ink 220 Ambitious 5 ml",
  "Tantum Verde Oral Rinse 60 ml",
  "Maxprinol Syrup 60 ml",
  "OBH Combi Anak Batuk Plus Flu Jeruk 60 ml",
  "Bagus Sikat Gigi Moo Soft",
  "Baby Safe Plate",
  "Opimox 500 mg 10 Kaplet",
  "Cici Cat Wet Food Fresh Tuna 400 g",
  "Triamcort 4 mg 10 Tablet",
  "Curcuma Plus Fruit and Veggie Strawberry Sirup 100 ml",
  "Royal Canin Adult Dog Medium Adult 140 g",
  "Physiomer Normal Jet Nasal Spray 135 ml",
  "Happy Cat Vet Adult Skin Wet Food 100 g",
  "Serenity Headset Hearing Aid SR-80P",
  "Simbado 10 mg 10 Tablet",
  "Xylitol SF Blueberry 30 g",
  "Kasa Steril Dinda Biru 16 X 16 cm 16 Lembar",
  "Super Cat Liquid Snack Chicken With Shrimp 4 Sachet",
  "Erlamol Forte 650 mg 10 Kaplet",
  "DoCare Wash Gloves 4 Sheet Parfume",
  "Lifree Popok Dewasa Celana Xl 3 Pieces",
  "Blackmores Vision Support 30 Kapsul",
  "Charm Body Fit Extra Maxi Non Wing 10 Pads",
  "Fasidol 500 mg 10 Kaplet",
  "Chil Kid 3 Soya Vanila 200 gr",
  "Clinelle PureSwiss Hydracalm Cleansing Gel 100 ml",
  "Baby Huki Dot Orthodontic Silicone Nipple L 3 Pieces",
  "Glutathionic 30 Kaplet",
  "Pulmicort 0.5 mg/ml 4 Strip (5 Respules/Strip) - Obat Rutin",
  "Pepsodent Tooth Paste Action 123 Herbal 190 g",
  "Larutan Cap Kaki Tiga Anak Apel 250 ml",
  "Morinaga BMT Platinum 800 g",
  "Labore Sensitive Skin Care Biomerepair Barrier Revive Cream 10 ml",
  "Enaplex-C Multivitamin 6 Kaplet",
  "Sifrol",
  "Narmig 25 mg 10 Tablet",
  "Neuroaid II (MLC 901) 12 Kapsul",
  "Formula Sikat Gigi Flip Go Nano Charcoal Slim",
  "Konilife Oxi 30 Kapsul",
  "Princess Excellence Chicken",
  "Neurofenac Plus 50 mg 10 Tablet",
  "Blood Neckheat Sachet",
  "Albiruni Albiguraa 25 Kapsul",
  "Vienna Whitening Body Scrub Cows Milk 50 g",
  "Kelo-Cote Gel 6 Gram",
  "Milna Nature Delight Apple Banana Strawberry 80 g",
  "Pocari Sweat 350 ml",
  "Hemocap 4 Kapsul",
  "Aciblock 150 mg 10 Tablet",
  "Mamy Love Pants M 9 Pieces",
  "Pharflox 400 mg 10 Tablet",
  "Lexapram Sirup 60 ml",
  "Torasic 10 mg 10 Tablet",
  "Baby Safe Collapsible Food Container 540 ml SC02",
  "Maybelline Lipstick Superstay Matte Ink 335 Hustler 5 ml",
  "Interdoxin 100 mg 4 Kapsul",
  "GetVit-C/Provit-C 605 mg 30 Kaplet",
  "Nutrimax Wild Yam Extract 30 Kapsul",
  "Watsons Omega-3 Fish Oil 1000 90 Kapsul",
  "Fresh Eye Premium No Rub Multi Purpose Solution 360 ml",
  "Proris Triple Action 10 Kaplet",
  "Evian Baby Brumisateur Face & Body Spray 150 ml",
  "Yuri Hand Soap Grape Pump 410 ml",
  "Benadryl Batuk Berdahak Sirup 50 ml",
  "Olay Total Effects Anti Ageing Serum 50 ml",
  "Garnier Sakura White Tissu Mask Pinkish Radiance",
  "Pureluxe Grain Free Holistic Healthy Weight Dog With Turkey",
  "Thromboflash Gel 20 gr",
  "Frozz Permen Orange 15 g",
  "Loreal Lipstick Rouge Signature 145 I Convince",
  "uegwhkb uegwhkb",
  "fferzmp fferzmp",
  "hpt hpt",
  "qgjcb qgjcb",
  "ywiddnp",
  "fpbczdh",
  "uqey",
  "uhkss",
  "ymjgq",
  "xoymo",
  "pzl",
  "twvelp",
  "rue",
  "qdhy",
  "umvtat",
  "akcvvcvu",
  "botsel",
  "bfsw",
  "qgk",
  "nxrcrz",
  "srnx",
  "jzw",
  "damf",
  "ttkq",
  "zwp",
  "vsxisnko",
  "ybplqzgv",
  "lkdt",
  "agsdtzn",
  "ejc",
  "evbvtbt",
  "qugjw",
  "ifog",
  "twhwkvr",
  "obuxx",
  "afodt",
  "hfzfdue",
  "hnqhknn",
  "enrckz",
  "ics",
  "bjm",
  "iwohqfc",
  "woidor",
  "kyp",
  "zpn",
  "uvbvsq",
  "jjtou",
  "finy",
  "edqxfh",
  "tpkrh",
  "nul",
  "ojel",
  "qru",
  "osyeer",
  "snp",
  "gavaop",
  "fmfkz",
  "nbo",
  "aezuqjnu",
  "npbgklwj",
  "dyh",
  "uofom",
  "hyz",
  "jrcoj",
  "ojpttnh",
  "vwssoy",
  "epel",
  "dcyimjzk",
  "mqgejz",
  "rfzcdzdt",
  "lclyejir",
  "nblskj",
  "alyu",
  "gxmje",
  "lfzqby",
  "qny",
  "emapl",
  "keoggjs",
  "vsfarxbm",
  "zcs",
  "tln",
  "okzsqztn",
  "dlspegt",
  "ilkpl",
  "ekdbjtr",
  "ofjpjlp",
  "thzqumyi",
  "sbuqvut",
  "fzafwc",
  "oiuzt",
  "leue",
  "swtslo",
  "pyehsd",
  "afpt",
  "qewk",
  "ycjalt",
  "vrbf",
  "xtxhapgm",
  "wxcuzuda",
  "hqfjb",
];
